import type { NotesFile } from "./types";

export const cloudDevopsNotes: NotesFile = {
  meta: {
    title: "Cloud & DevOps — the whole map",
    subtitle: "24 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: { figure: "" },

  chapters: [
    {
      id: "cloud-fundamentals",
      num: "B1",
      title: "Cloud computing fundamentals",
      short: "Cloud fundamentals",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-compute-basics",
      num: "B2",
      title: "Compute basics",
      short: "Compute basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-storage-basics",
      num: "B3",
      title: "Storage basics",
      short: "Storage basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-networking-basics",
      num: "B4",
      title: "Networking basics",
      short: "Networking basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-iam-basics",
      num: "B5",
      title: "IAM",
      short: "IAM",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-first-deploy",
      num: "B6",
      title: "Deploying a simple app",
      short: "First deploy",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-provider-landscape",
      num: "B7",
      title: "The cloud provider landscape",
      short: "Provider landscape",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "cloud-managed-databases",
      num: "I1",
      title: "Managed databases",
      short: "Managed databases",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-load-balancing-autoscaling",
      num: "I2",
      title: "Load balancers & auto-scaling",
      short: "Load balancing & autoscaling",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-serverless-depth",
      num: "I3",
      title: "Serverless in depth",
      short: "Serverless in depth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-iac",
      num: "I4",
      title: "Infrastructure as Code",
      short: "IaC",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-ci-cd",
      num: "I5",
      title: "CI/CD pipelines in the cloud",
      short: "CI/CD in the cloud",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-monitoring-logging",
      num: "I6",
      title: "Monitoring & logging",
      short: "Monitoring & logging",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-environments-config",
      num: "I7",
      title: "Environments & config",
      short: "Environments & config",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-cdn-edge",
      num: "I8",
      title: "CDN & edge",
      short: "CDN & edge",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-cost-management",
      num: "I9",
      title: "Cost management",
      short: "Cost management",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "cloud-multiregion-ha",
      num: "A1",
      title: "Multi-region & high availability",
      short: "Multi-region & HA",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-container-services",
      num: "A2",
      title: "Container services",
      short: "Container services",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-advanced-iam",
      num: "A3",
      title: "Advanced IAM",
      short: "Advanced IAM",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-disaster-recovery",
      num: "A4",
      title: "Disaster recovery",
      short: "Disaster recovery",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-observability-scale",
      num: "A5",
      title: "Observability at scale",
      short: "Observability at scale",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-security",
      num: "A6",
      title: "Security in the cloud",
      short: "Security in the cloud",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-landing-zones",
      num: "A7",
      title: "Landing zones & multi-account strategy",
      short: "Landing zones",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "cloud-finops",
      num: "A8",
      title: "FinOps",
      short: "FinOps",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
