import type { NotesFile } from "./types";

export const cssNotes: NotesFile = {
  meta: {
    title: "CSS — the whole map",
    subtitle: "25 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: { figure: "" },

  chapters: [
    {
      id: "css-cascade-specificity",
      num: "B1",
      title: "The cascade, specificity & inheritance",
      short: "Cascade & specificity",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-box-model",
      num: "B2",
      title: "The box model",
      short: "The box model",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-selectors",
      num: "B3",
      title: "Selectors",
      short: "Selectors",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-display-types",
      num: "B4",
      title: "Display types",
      short: "Display types",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-colors-units-typography",
      num: "B5",
      title: "Colors, units & typography",
      short: "Colors & typography",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-backgrounds-borders",
      num: "B6",
      title: "Backgrounds & borders",
      short: "Backgrounds & borders",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-flexbox",
      num: "B7",
      title: "Flexbox",
      short: "Flexbox",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-responsive-basics",
      num: "B8",
      title: "Basic responsive design",
      short: "Responsive basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "css-grid",
      num: "I1",
      title: "Grid",
      short: "Grid",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-positioning-stacking",
      num: "I2",
      title: "Positioning & stacking contexts",
      short: "Positioning & stacking",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-transitions-animations",
      num: "I3",
      title: "Transitions & animations",
      short: "Transitions & animations",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-custom-properties",
      num: "I4",
      title: "Custom properties",
      short: "Custom properties",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-responsive-depth",
      num: "I5",
      title: "Responsive design in depth",
      short: "Responsive in depth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-architecture",
      num: "I6",
      title: "CSS architecture",
      short: "CSS architecture",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-selectors-depth",
      num: "I7",
      title: "Pseudo-classes & selectors in depth",
      short: "Selectors in depth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-media-types",
      num: "I8",
      title: "Print & other media types",
      short: "Media types",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-forms-styling",
      num: "I9",
      title: "Forms styling",
      short: "Forms styling",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "css-layout-algorithms-depth",
      num: "A1",
      title: "Stacking contexts & layout algorithms in depth",
      short: "Layout algorithms",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-advanced-animation",
      num: "A2",
      title: "Advanced animation",
      short: "Advanced animation",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-architecture-scale",
      num: "A3",
      title: "CSS architecture at scale",
      short: "Architecture at scale",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-performance",
      num: "A4",
      title: "Performance",
      short: "Performance",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-modern-layout",
      num: "A5",
      title: "Modern layout techniques",
      short: "Modern layout",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-cascade-layers-scope",
      num: "A6",
      title: "Cascade layers & scope",
      short: "Cascade layers & scope",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-houdini",
      num: "A7",
      title: "Houdini & the future of CSS",
      short: "Houdini",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "css-cross-browser",
      num: "A8",
      title: "Cross-browser & fallback strategies",
      short: "Cross-browser strategies",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
