import type { NotesFile } from "./types";

export const databasesNotes: NotesFile = {
  meta: {
    title: "SQL & Databases — the whole map",
    subtitle: "25 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: { figure: "" },

  chapters: [
    {
      id: "sql-relational-model",
      num: "B1",
      title: "The relational model",
      short: "Relational model",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-select-fundamentals",
      num: "B2",
      title: "SELECT fundamentals",
      short: "SELECT fundamentals",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-joins",
      num: "B3",
      title: "Joins",
      short: "Joins",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-aggregations",
      num: "B4",
      title: "Aggregations",
      short: "Aggregations",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-insert-update-delete",
      num: "B5",
      title: "Inserting, updating, deleting",
      short: "Insert/update/delete",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-data-types-constraints",
      num: "B6",
      title: "Data types & constraints",
      short: "Types & constraints",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-schema-design-basics",
      num: "B7",
      title: "Basic schema design",
      short: "Schema design basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-db-client-basics",
      num: "B8",
      title: "Using a database client",
      short: "Using a DB client",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "sql-normalization-depth",
      num: "I1",
      title: "Normalization in depth",
      short: "Normalization in depth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-indexes",
      num: "I2",
      title: "Indexes",
      short: "Indexes",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-transactions",
      num: "I3",
      title: "Transactions",
      short: "Transactions",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-subqueries-ctes",
      num: "I4",
      title: "Subqueries & CTEs",
      short: "Subqueries & CTEs",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-query-performance",
      num: "I5",
      title: "Query performance",
      short: "Query performance",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-nosql-fundamentals",
      num: "I6",
      title: "NoSQL fundamentals",
      short: "NoSQL fundamentals",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-orms",
      num: "I7",
      title: "ORMs",
      short: "ORMs",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-migrations",
      num: "I8",
      title: "Migrations",
      short: "Migrations",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-backups-replication",
      num: "I9",
      title: "Backups & replication basics",
      short: "Backups & replication",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "sql-database-internals",
      num: "A1",
      title: "Database internals",
      short: "Database internals",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-scaling-reads",
      num: "A2",
      title: "Scaling reads",
      short: "Scaling reads",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-scaling-writes",
      num: "A3",
      title: "Scaling writes",
      short: "Scaling writes",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-advanced-transactions",
      num: "A4",
      title: "Advanced transactions",
      short: "Advanced transactions",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-caching-layers",
      num: "A5",
      title: "Caching layers in front of a database",
      short: "Caching layers",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-security-depth",
      num: "A6",
      title: "Database security in depth",
      short: "Security in depth",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-timeseries-analytical",
      num: "A7",
      title: "Time-series & analytical databases",
      short: "Time-series & analytical",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "sql-schema-case-study",
      num: "A8",
      title: "Designing a schema for a real system",
      short: "Schema case study",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
