import type { NotesFile } from "./types";

export const dockerNotes: NotesFile = {
  meta: {
    title: "Docker — the whole map",
    subtitle: "22 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: { figure: "" },

  chapters: [
    {
      id: "docker-what-are-containers",
      num: "B1",
      title: "What containers are",
      short: "What containers are",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-dockerfile-basics",
      num: "B2",
      title: "Dockerfile basics",
      short: "Dockerfile basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-running-containers",
      num: "B3",
      title: "Running containers",
      short: "Running containers",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-cli",
      num: "B4",
      title: "The Docker CLI",
      short: "The Docker CLI",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-dockerignore-context",
      num: "B5",
      title: ".dockerignore & build context",
      short: "Build context",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-multistage-builds-intro",
      num: "B6",
      title: "Multi-stage builds (intro)",
      short: "Multi-stage builds intro",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-compose-basics",
      num: "B7",
      title: "Docker Compose basics",
      short: "Compose basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "docker-dockerfile-best-practices",
      num: "I1",
      title: "Dockerfile best practices",
      short: "Dockerfile best practices",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-networking",
      num: "I2",
      title: "Networking",
      short: "Networking",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-volumes-persistence",
      num: "I3",
      title: "Volumes & persistence",
      short: "Volumes & persistence",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-compose-depth",
      num: "I4",
      title: "Docker Compose in depth",
      short: "Compose in depth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-env-configs",
      num: "I5",
      title: "Environment-specific configs",
      short: "Env-specific configs",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-debugging",
      num: "I6",
      title: "Debugging containers",
      short: "Debugging containers",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-registries",
      num: "I7",
      title: "Registries",
      short: "Registries",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-ci-cd",
      num: "I8",
      title: "Docker with CI/CD",
      short: "Docker with CI/CD",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "docker-orchestration-basics",
      num: "A1",
      title: "Orchestration basics",
      short: "Orchestration basics",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-security",
      num: "A2",
      title: "Security",
      short: "Security",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-build-performance",
      num: "A3",
      title: "Build performance",
      short: "Build performance",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-production-compose-swarm",
      num: "A4",
      title: "Production Compose / Swarm",
      short: "Production Compose/Swarm",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-observability",
      num: "A5",
      title: "Observability for containers",
      short: "Observability",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-multiarch-builds",
      num: "A6",
      title: "Multi-arch builds",
      short: "Multi-arch builds",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "docker-internals",
      num: "A7",
      title: "Container internals",
      short: "Container internals",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
