import type { NotesFile } from "./types";

export const graphqlNotes: NotesFile = {
  meta: {
    title: "GraphQL — the whole map",
    subtitle: "22 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: { figure: "" },

  chapters: [
    {
      id: "graphql-what-why",
      num: "B1",
      title: "What GraphQL is & why",
      short: "What & why",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-schema-types",
      num: "B2",
      title: "Schema & types",
      short: "Schema & types",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-queries",
      num: "B3",
      title: "Queries",
      short: "Queries",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-mutations",
      num: "B4",
      title: "Mutations",
      short: "Mutations",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-resolvers",
      num: "B5",
      title: "Resolvers",
      short: "Resolvers",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-server-setup",
      num: "B6",
      title: "Setting up a GraphQL server",
      short: "Server setup",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-client-basics",
      num: "B7",
      title: "A GraphQL client",
      short: "Client basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "graphql-schema-design",
      num: "I1",
      title: "Schema design",
      short: "Schema design",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-n-plus-one-dataloader",
      num: "I2",
      title: "The N+1 problem & DataLoader",
      short: "N+1 & DataLoader",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-auth",
      num: "I3",
      title: "Authentication & authorization",
      short: "Auth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-error-handling",
      num: "I4",
      title: "Error handling",
      short: "Error handling",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-pagination",
      num: "I5",
      title: "Pagination patterns",
      short: "Pagination patterns",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-subscriptions",
      num: "I6",
      title: "Subscriptions",
      short: "Subscriptions",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-client-caching",
      num: "I7",
      title: "Caching in GraphQL clients",
      short: "Client caching",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-testing",
      num: "I8",
      title: "Testing a GraphQL API",
      short: "Testing",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "graphql-federation",
      num: "A1",
      title: "Federation & schema stitching",
      short: "Federation",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-performance",
      num: "A2",
      title: "Performance",
      short: "Performance",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-security",
      num: "A3",
      title: "Security in GraphQL",
      short: "Security",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-codefirst-schemafirst",
      num: "A4",
      title: "Code-first vs schema-first at scale",
      short: "Code-first vs schema-first",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-vs-rest-vs-trpc",
      num: "A5",
      title: "GraphQL vs REST vs tRPC",
      short: "vs REST vs tRPC",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-monitoring",
      num: "A6",
      title: "Monitoring a GraphQL API",
      short: "Monitoring",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "graphql-production-gateway",
      num: "A7",
      title: "A production-grade GraphQL gateway",
      short: "Production gateway",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
