import type { NotesFile } from "./types";

export const htmlNotes: NotesFile = {
  meta: {
    title: "HTML — the whole map",
    subtitle: "22 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: { figure: "" },

  chapters: [
    {
      id: "html-document-structure",
      num: "B1",
      title: "Document structure & the parser",
      short: "Document structure",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-semantic-elements",
      num: "B2",
      title: "Text & semantic elements",
      short: "Semantic elements",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-links-images-media",
      num: "B3",
      title: "Links, images & media",
      short: "Links, images & media",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-forms-basics",
      num: "B4",
      title: "Forms basics",
      short: "Forms basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-tables",
      num: "B5",
      title: "Tables",
      short: "Tables",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-attributes",
      num: "B6",
      title: "Attributes & global attributes",
      short: "Attributes",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-meta-head",
      num: "B7",
      title: "Meta tags & the document head",
      short: "Meta & document head",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "html-landmarks",
      num: "I1",
      title: "Semantic landmarks & document outline",
      short: "Landmarks",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-forms-depth",
      num: "I2",
      title: "Forms in depth",
      short: "Forms in depth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-accessibility-fundamentals",
      num: "I3",
      title: "Accessibility fundamentals",
      short: "Accessibility fundamentals",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-embedded-content",
      num: "I4",
      title: "Embedded content",
      short: "Embedded content",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-web-components-intro",
      num: "I5",
      title: "Web components (intro)",
      short: "Web components intro",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-structured-data",
      num: "I6",
      title: "Microdata & structured data",
      short: "Structured data",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-progressive-enhancement",
      num: "I7",
      title: "Progressive enhancement",
      short: "Progressive enhancement",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-constraint-validation",
      num: "I8",
      title: "The Constraint Validation API",
      short: "Constraint validation",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "html-accessibility-depth",
      num: "A1",
      title: "Accessibility in depth",
      short: "Accessibility in depth",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-performance",
      num: "A2",
      title: "Performance",
      short: "Performance",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-responsive-images",
      num: "A3",
      title: "Responsive images",
      short: "Responsive images",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-web-components-depth",
      num: "A4",
      title: "Web components in depth",
      short: "Web components in depth",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-security",
      num: "A5",
      title: "Security",
      short: "Security",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-parsing-algorithm",
      num: "A6",
      title: "The HTML parsing algorithm",
      short: "Parsing algorithm",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "html-seo-sharing-scale",
      num: "A7",
      title: "HTML for SEO & sharing at scale",
      short: "SEO & sharing at scale",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
