import type { NotesFile } from "./types";

export const kubernetesNotes: NotesFile = {
  meta: {
    title: "Kubernetes — the whole map",
    subtitle: "24 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: { figure: "" },

  chapters: [
    {
      id: "k8s-what-why",
      num: "B1",
      title: "What Kubernetes is & why",
      short: "What & why",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-core-objects",
      num: "B2",
      title: "Pods, Deployments & Services",
      short: "Core objects",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-kubectl-basics",
      num: "B3",
      title: "kubectl basics",
      short: "kubectl basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-namespaces-basics",
      num: "B4",
      title: "Namespaces & basic organization",
      short: "Namespaces",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-configmaps-secrets",
      num: "B5",
      title: "ConfigMaps & Secrets",
      short: "ConfigMaps & Secrets",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-local-cluster",
      num: "B6",
      title: "A local cluster",
      short: "A local cluster",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-yaml-manifests",
      num: "B7",
      title: "YAML manifests",
      short: "YAML manifests",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "k8s-deployments-depth",
      num: "I1",
      title: "Deployments in depth",
      short: "Deployments in depth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-services-networking",
      num: "I2",
      title: "Services & networking",
      short: "Services & networking",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-persistent-storage",
      num: "I3",
      title: "Persistent storage",
      short: "Persistent storage",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-health-checks",
      num: "I4",
      title: "Health checks",
      short: "Health checks",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-resource-management",
      num: "I5",
      title: "Resource management",
      short: "Resource management",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-helm",
      num: "I6",
      title: "Helm",
      short: "Helm",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-rbac",
      num: "I7",
      title: "Namespaces & RBAC",
      short: "RBAC",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-ci-cd",
      num: "I8",
      title: "CI/CD to Kubernetes",
      short: "CI/CD to Kubernetes",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-debugging",
      num: "I9",
      title: "Debugging a cluster",
      short: "Debugging a cluster",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "k8s-cluster-architecture",
      num: "A1",
      title: "Cluster architecture",
      short: "Cluster architecture",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-crds-operators",
      num: "A2",
      title: "Custom Resources & Operators",
      short: "CRDs & Operators",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-service-mesh",
      num: "A3",
      title: "Service meshes",
      short: "Service meshes",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-multicluster-multitenancy",
      num: "A4",
      title: "Multi-cluster & multi-tenancy",
      short: "Multi-cluster",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-security",
      num: "A5",
      title: "Security",
      short: "Security",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-observability",
      num: "A6",
      title: "Observability",
      short: "Observability",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-cost-optimization",
      num: "A7",
      title: "Cost & resource optimization",
      short: "Cost optimization",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "k8s-gitops",
      num: "A8",
      title: "GitOps",
      short: "GitOps",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
