import type { NotesFile } from "./types";

export const nestjsNotes: NotesFile = {
  meta: {
    title: "Nest.js — the whole map",
    subtitle: "26 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: { figure: "" },

  chapters: [
    {
      id: "nest-setup-cli",
      num: "B1",
      title: "Project setup & the Nest CLI",
      short: "Setup & CLI",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-controllers-routing",
      num: "B2",
      title: "Controllers & routing",
      short: "Controllers & routing",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-providers-di-basics",
      num: "B3",
      title: "Providers & dependency injection",
      short: "Providers & DI basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-modules",
      num: "B4",
      title: "Modules",
      short: "Modules",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-validation-basics",
      num: "B5",
      title: "Basic validation",
      short: "Validation basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-configuration",
      num: "B6",
      title: "Configuration",
      short: "Configuration",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-database-basics",
      num: "B7",
      title: "Connecting a database (basics)",
      short: "Database basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-first-resource",
      num: "B8",
      title: "Building your first CRUD resource",
      short: "First resource",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "nest-di-depth",
      num: "I1",
      title: "Dependency injection in depth",
      short: "DI in depth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-pipes-guards-interceptors",
      num: "I2",
      title: "Pipes, guards & interceptors",
      short: "Pipes, guards & interceptors",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-middleware",
      num: "I3",
      title: "Middleware in Nest",
      short: "Middleware",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-exception-filters",
      num: "I4",
      title: "Exception filters",
      short: "Exception filters",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-authentication",
      num: "I5",
      title: "Authentication",
      short: "Authentication",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-authorization",
      num: "I6",
      title: "Authorization",
      short: "Authorization",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-testing",
      num: "I7",
      title: "Testing in Nest",
      short: "Testing",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-repository-patterns",
      num: "I8",
      title: "Database & repository patterns",
      short: "Repository patterns",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-openapi-swagger",
      num: "I9",
      title: "OpenAPI/Swagger integration",
      short: "OpenAPI/Swagger",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-scheduling-queues",
      num: "I10",
      title: "Task scheduling & queues",
      short: "Scheduling & queues",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "nest-microservices",
      num: "A1",
      title: "Microservices with Nest",
      short: "Microservices",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-graphql",
      num: "A2",
      title: "GraphQL with Nest",
      short: "GraphQL",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-websockets-gateways",
      num: "A3",
      title: "WebSockets & gateways",
      short: "WebSockets & gateways",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-custom-decorators",
      num: "A4",
      title: "Custom decorators & metadata reflection",
      short: "Custom decorators",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-advanced-modules",
      num: "A5",
      title: "Advanced module patterns",
      short: "Advanced module patterns",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-performance-caching",
      num: "A6",
      title: "Performance & caching",
      short: "Performance & caching",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-monorepo",
      num: "A7",
      title: "Monorepo Nest apps",
      short: "Monorepo Nest apps",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "nest-production-readiness",
      num: "A8",
      title: "Production readiness",
      short: "Production readiness",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
