import type { NotesFile } from "./types";

export const nextjsNotes: NotesFile = {
  meta: {
    title: "Next.js — the whole map",
    subtitle: "29 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: { figure: "" },

  chapters: [
    {
      id: "next-setup",
      num: "B1",
      title: "What Next.js is & project setup",
      short: "Setup",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-app-router",
      num: "B2",
      title: "The App Router",
      short: "The App Router",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-routing",
      num: "B3",
      title: "Routing",
      short: "Routing",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-rendering-basics",
      num: "B4",
      title: "Rendering basics",
      short: "Rendering basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-data-fetching-basic",
      num: "B5",
      title: "Data fetching (basic)",
      short: "Data fetching basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-styling",
      num: "B6",
      title: "Styling in Next",
      short: "Styling",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-images-fonts",
      num: "B7",
      title: "Images & fonts",
      short: "Images & fonts",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-linking-navigation",
      num: "B8",
      title: "Linking & navigation",
      short: "Linking & navigation",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "next-server-client-components",
      num: "I1",
      title: "Server vs Client Components",
      short: "Server vs Client",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-parallel-intercepting-routes",
      num: "I2",
      title: "Parallel & intercepting routes",
      short: "Parallel & intercepting",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-data-fetching-depth",
      num: "I3",
      title: "Data fetching in depth",
      short: "Data fetching in depth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-route-handlers",
      num: "I4",
      title: "API routes / Route Handlers",
      short: "Route Handlers",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-server-actions",
      num: "I5",
      title: "Server Actions",
      short: "Server Actions",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-middleware",
      num: "I6",
      title: "Middleware",
      short: "Middleware",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-metadata-seo",
      num: "I7",
      title: "Metadata & SEO",
      short: "Metadata & SEO",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-env-config",
      num: "I8",
      title: "Environment & config",
      short: "Environment & config",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-auth",
      num: "I9",
      title: "Authentication in Next",
      short: "Authentication",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-error-handling",
      num: "I10",
      title: "Error handling",
      short: "Error handling",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-testing",
      num: "I11",
      title: "Testing a Next app",
      short: "Testing",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "next-rendering-depth",
      num: "A1",
      title: "Rendering strategies in depth",
      short: "Rendering strategies",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-caching-architecture",
      num: "A2",
      title: "Caching architecture",
      short: "Caching architecture",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-performance",
      num: "A3",
      title: "Performance",
      short: "Performance",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-deployment",
      num: "A4",
      title: "Deployment",
      short: "Deployment",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-i18n",
      num: "A5",
      title: "Internationalization",
      short: "i18n",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-monorepos",
      num: "A6",
      title: "Monorepos with Next.js",
      short: "Monorepos",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-server-actions-advanced",
      num: "A7",
      title: "Advanced Server Actions patterns",
      short: "Server Actions, advanced",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-databases",
      num: "A8",
      title: "Databases in Next",
      short: "Databases in Next",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-security",
      num: "A9",
      title: "Security in Next",
      short: "Security",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "next-migration",
      num: "A10",
      title: "Migrating Pages Router to App Router",
      short: "Pages → App migration",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
