import type { NotesFile } from "./types";

export const nodeNotes: NotesFile = {
  meta: {
    title: "Node.js — the whole map",
    subtitle: "41 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: {
    figure: "",
  },

  chapters: [
    {
      id: "node-runtime-tooling",
      num: "B1",
      title: "Runtime & tooling",
      short: "Runtime & tooling",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-modules-npm",
      num: "B2",
      title: "Modules & npm",
      short: "Modules & npm",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-fs-paths",
      num: "B3",
      title: "File system & paths",
      short: "File system & paths",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-http-core",
      num: "B4",
      title: "Core HTTP",
      short: "Core HTTP",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-express-basics",
      num: "B5",
      title: "Express basics",
      short: "Express basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-env-config",
      num: "B6",
      title: "Environment & config",
      short: "Environment & config",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-async",
      num: "B7",
      title: "Async in Node",
      short: "Async in Node",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-error-handling-debugging",
      num: "B8",
      title: "Error handling & debugging",
      short: "Error handling",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-first-api",
      num: "B9",
      title: "Building your first API",
      short: "First API",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "node-event-loop",
      num: "I1",
      title: "The event loop in Node",
      short: "Event loop",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-event-emitter",
      num: "I2",
      title: "EventEmitter & the observer pattern",
      short: "EventEmitter",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-streams-buffers",
      num: "I3",
      title: "Streams & buffers",
      short: "Streams & buffers",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-rest-apis-scale",
      num: "I4",
      title: "REST APIs at scale",
      short: "REST APIs at scale",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-api-design",
      num: "I5",
      title: "REST API design principles",
      short: "API design principles",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-databases",
      num: "I6",
      title: "Databases",
      short: "Databases",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-caching",
      num: "I7",
      title: "Caching with Redis",
      short: "Caching",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-auth-sessions",
      num: "I8",
      title: "Authentication & sessions",
      short: "Auth & sessions",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-testing",
      num: "I9",
      title: "Testing Node apps",
      short: "Testing",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-child-processes-os",
      num: "I10",
      title: "Child processes & the OS",
      short: "Child processes & OS",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-logging-monitoring",
      num: "I11",
      title: "Logging & monitoring",
      short: "Logging & monitoring",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-security-fundamentals",
      num: "I12",
      title: "Security fundamentals",
      short: "Security fundamentals",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-websockets",
      num: "I13",
      title: "Real-time with WebSockets",
      short: "WebSockets",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-background-jobs",
      num: "I14",
      title: "Background jobs & queues",
      short: "Background jobs & queues",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-deployment-basics",
      num: "I15",
      title: "Deployment basics",
      short: "Deployment basics",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "node-internals",
      num: "A1",
      title: "Node internals",
      short: "Node internals",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-worker-threads-clustering",
      num: "A2",
      title: "Worker threads & clustering",
      short: "Worker threads & clustering",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-streams-scale",
      num: "A3",
      title: "Streams at scale",
      short: "Streams at scale",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-performance-profiling",
      num: "A4",
      title: "Performance & profiling",
      short: "Performance & profiling",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-async-local-storage",
      num: "A5",
      title: "AsyncLocalStorage & async_hooks",
      short: "AsyncLocalStorage",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-scalable-architectures",
      num: "A6",
      title: "Scalable architectures",
      short: "Scalable architectures",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-message-queues",
      num: "A7",
      title: "Message queues & event-driven systems",
      short: "Message queues",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-serverless",
      num: "A8",
      title: "Serverless architectures",
      short: "Serverless",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-graphql-apis",
      num: "A9",
      title: "GraphQL & advanced APIs",
      short: "GraphQL & APIs",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-security-depth",
      num: "A10",
      title: "Security in depth",
      short: "Security in depth",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-native-addons",
      num: "A11",
      title: "Native addons",
      short: "Native addons",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-observability",
      num: "A12",
      title: "Observability",
      short: "Observability",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-typescript-scale",
      num: "A13",
      title: "TypeScript in Node at scale",
      short: "TypeScript at scale",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-build-tooling-monorepos",
      num: "A14",
      title: "Build tooling & monorepos",
      short: "Build tooling & monorepos",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-ci-cd",
      num: "A15",
      title: "CI/CD pipelines",
      short: "CI/CD pipelines",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-production-readiness",
      num: "A16",
      title: "Production readiness",
      short: "Production readiness",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "node-advanced-http",
      num: "A17",
      title: "Advanced HTTP",
      short: "Advanced HTTP",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
