import type { NotesFile } from "./types";

export const reactNotes: NotesFile = {
  meta: {
    title: "React — the whole map",
    subtitle: "41 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: {
    figure: "",
  },

  chapters: [
    {
      id: "react-setup-jsx",
      num: "B1",
      title: "Project setup & JSX",
      short: "Setup & JSX",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-components",
      num: "B2",
      title: "Components & composition",
      short: "Components & composition",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-props",
      num: "B3",
      title: "Props",
      short: "Props",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-usestate",
      num: "B4",
      title: "State with useState",
      short: "useState",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-events-conditionals",
      num: "B5",
      title: "Events & conditional rendering",
      short: "Events & conditionals",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-lists-keys",
      num: "B6",
      title: "Lists with .map() and keys",
      short: "Lists & keys",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-forms",
      num: "B7",
      title: "Controlled forms",
      short: "Controlled forms",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-useeffect-basics",
      num: "B8",
      title: "useEffect basics",
      short: "useEffect basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-lifting-styling",
      num: "B9",
      title: "Lifting state up & basic styling",
      short: "Lifting state & styling",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "react-useref",
      num: "I1",
      title: "useRef",
      short: "useRef",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-context",
      num: "I2",
      title: "Context API",
      short: "Context API",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-usereducer",
      num: "I3",
      title: "useReducer",
      short: "useReducer",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-custom-hooks",
      num: "I4",
      title: "Custom hooks",
      short: "Custom hooks",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-effects-depth",
      num: "I5",
      title: "Effects in depth",
      short: "Effects in depth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-router",
      num: "I6",
      title: "React Router",
      short: "React Router",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-state-architecture",
      num: "I7",
      title: "State architecture",
      short: "State architecture",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-memoisation",
      num: "I8",
      title: "Memoisation",
      short: "Memoisation",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-boundaries-portals",
      num: "I9",
      title: "Error boundaries, portals & keys in depth",
      short: "Boundaries & portals",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-data-fetching",
      num: "I10",
      title: "Data fetching patterns",
      short: "Data fetching patterns",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-forms-at-scale",
      num: "I11",
      title: "Forms at scale",
      short: "Forms at scale",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-state-libraries",
      num: "I12",
      title: "State management libraries",
      short: "State libraries",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-server-state",
      num: "I13",
      title: "Server state with TanStack Query",
      short: "Server state",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-testing",
      num: "I14",
      title: "Testing React",
      short: "Testing React",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-typescript",
      num: "I15",
      title: "TypeScript with React",
      short: "TypeScript with React",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "react-fiber",
      num: "A1",
      title: "Reconciliation & Fiber",
      short: "Reconciliation & Fiber",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-concurrent",
      num: "A2",
      title: "Concurrent features",
      short: "Concurrent features",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-suspense",
      num: "A3",
      title: "Suspense & code splitting",
      short: "Suspense & code splitting",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-server-components",
      num: "A4",
      title: "Server Components",
      short: "Server Components",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-server-actions",
      num: "A5",
      title: "Server Actions",
      short: "Server Actions",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-use-hook",
      num: "A6",
      title: "The use() hook",
      short: "The use() hook",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-rendering-strategies",
      num: "A7",
      title: "Rendering strategies",
      short: "Rendering strategies",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-effect-timing",
      num: "A8",
      title: "Effect timing",
      short: "Effect timing",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-sync-external-store",
      num: "A9",
      title: "useSyncExternalStore",
      short: "useSyncExternalStore",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-refs-depth",
      num: "A10",
      title: "Refs in depth",
      short: "Refs in depth",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-advanced-patterns",
      num: "A11",
      title: "Advanced component patterns",
      short: "Advanced patterns",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-performance",
      num: "A12",
      title: "Performance work",
      short: "Performance",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-accessibility",
      num: "A13",
      title: "Accessibility",
      short: "Accessibility",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-design-systems",
      num: "A14",
      title: "Design systems",
      short: "Design systems",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-advanced-typescript",
      num: "A15",
      title: "Advanced TypeScript with React",
      short: "Advanced TypeScript",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-architecture-scale",
      num: "A16",
      title: "Architecture at scale",
      short: "Architecture at scale",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "react-custom-renderers",
      num: "A17",
      title: "Custom renderers",
      short: "Custom renderers",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
