import type { NotesFile } from "./types";

export const redisNotes: NotesFile = {
  meta: {
    title: "Redis — the whole map",
    subtitle: "21 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: { figure: "" },

  chapters: [
    {
      id: "redis-what-is-it",
      num: "B1",
      title: "What Redis is",
      short: "What Redis is",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-data-types-basics",
      num: "B2",
      title: "Basic data types",
      short: "Basic data types",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-setup-connecting",
      num: "B3",
      title: "Setting up & connecting",
      short: "Setup & connecting",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-ttls",
      num: "B4",
      title: "Expiration & TTLs",
      short: "TTLs",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-cache-aside",
      num: "B5",
      title: "Redis as a cache",
      short: "Redis as a cache",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-caching-example",
      num: "B6",
      title: "A caching example end to end",
      short: "Caching example",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "redis-pubsub",
      num: "I1",
      title: "Pub/Sub",
      short: "Pub/Sub",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-session-store",
      num: "I2",
      title: "Redis as a session store",
      short: "Session store",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-rate-limiting",
      num: "I3",
      title: "Rate limiting with Redis",
      short: "Rate limiting",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-queues",
      num: "I4",
      title: "Redis for queues",
      short: "Redis for queues",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-persistence",
      num: "I5",
      title: "Persistence",
      short: "Persistence",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-data-structures-depth",
      num: "I6",
      title: "Data structures in depth",
      short: "Data structures in depth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-transactions",
      num: "I7",
      title: "Transactions in Redis",
      short: "Transactions",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-real-app-connection",
      num: "I8",
      title: "Connecting Redis to a real app",
      short: "Real app connection",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "redis-cluster",
      num: "A1",
      title: "Redis Cluster",
      short: "Redis Cluster",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-high-availability",
      num: "A2",
      title: "High availability",
      short: "High availability",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-performance-tuning",
      num: "A3",
      title: "Performance tuning",
      short: "Performance tuning",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-primary-datastore",
      num: "A4",
      title: "Redis as a primary datastore",
      short: "Primary datastore",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-streams",
      num: "A5",
      title: "Redis Streams",
      short: "Redis Streams",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-security",
      num: "A6",
      title: "Security",
      short: "Security",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "redis-scaling-production",
      num: "A7",
      title: "Scaling Redis in production",
      short: "Scaling in production",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
