import type { NotesFile } from "./types";

export const securityNotes: NotesFile = {
  meta: {
    title: "Web Security — the whole map",
    subtitle: "24 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: { figure: "" },

  chapters: [
    {
      id: "security-mindset",
      num: "B1",
      title: "The security mindset",
      short: "The security mindset",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-injection",
      num: "B2",
      title: "Injection attacks",
      short: "Injection attacks",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-xss",
      num: "B3",
      title: "Cross-Site Scripting (XSS)",
      short: "XSS",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-auth-basics",
      num: "B4",
      title: "Authentication basics",
      short: "Auth basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-transport",
      num: "B5",
      title: "HTTPS & transport security",
      short: "Transport security",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-data-exposure",
      num: "B6",
      title: "Sensitive data exposure",
      short: "Sensitive data exposure",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-headers",
      num: "B7",
      title: "Security headers",
      short: "Security headers",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "security-csrf",
      num: "I1",
      title: "CSRF",
      short: "CSRF",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-access-control",
      num: "I2",
      title: "Broken access control",
      short: "Access control",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-session-management",
      num: "I3",
      title: "Session management",
      short: "Session management",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-oauth-oidc",
      num: "I4",
      title: "OAuth & OpenID Connect",
      short: "OAuth & OIDC",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-api",
      num: "I5",
      title: "API security",
      short: "API security",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-supply-chain",
      num: "I6",
      title: "Dependency & supply-chain security",
      short: "Supply-chain security",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-cors-depth",
      num: "I7",
      title: "CORS in depth",
      short: "CORS in depth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-misconfiguration",
      num: "I8",
      title: "Security misconfiguration",
      short: "Misconfiguration",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-secrets",
      num: "I9",
      title: "Secrets management",
      short: "Secrets management",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "security-owasp-top-10",
      num: "A1",
      title: "The OWASP Top 10",
      short: "OWASP Top 10",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-prototype-pollution-deserialization",
      num: "A2",
      title: "Prototype pollution & deserialization attacks",
      short: "Prototype pollution",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-ssrf",
      num: "A3",
      title: "Server-Side Request Forgery (SSRF)",
      short: "SSRF",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-testing-tools",
      num: "A4",
      title: "Security testing",
      short: "Security testing tools",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-cryptography",
      num: "A5",
      title: "Cryptography for developers",
      short: "Cryptography",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-zero-trust",
      num: "A6",
      title: "Zero trust & defense in depth",
      short: "Zero trust",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-incident-response",
      num: "A7",
      title: "Incident response",
      short: "Incident response",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "security-compliance-basics",
      num: "A8",
      title: "Compliance basics",
      short: "Compliance basics",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
