import type { NotesFile } from "./types";

export const testingNotes: NotesFile = {
  meta: {
    title: "Testing — the whole map",
    subtitle: "24 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: { figure: "" },

  chapters: [
    {
      id: "testing-why-pyramid",
      num: "B1",
      title: "Why we test",
      short: "Why we test",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-unit-fundamentals",
      num: "B2",
      title: "Unit testing fundamentals",
      short: "Unit testing fundamentals",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-pure-functions",
      num: "B3",
      title: "Testing pure functions",
      short: "Testing pure functions",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-mocking-basics",
      num: "B4",
      title: "Mocking basics",
      short: "Mocking basics",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-async-code",
      num: "B5",
      title: "Testing async code",
      short: "Testing async code",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-code-coverage",
      num: "B6",
      title: "Code coverage",
      short: "Code coverage",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-in-ci",
      num: "B7",
      title: "Running tests in CI",
      short: "Tests in CI",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "testing-tdd",
      num: "I1",
      title: "Test-driven development",
      short: "TDD",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-ui-components",
      num: "I2",
      title: "Testing UI components",
      short: "Testing UI components",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-apis-backends",
      num: "I3",
      title: "Testing APIs & backends",
      short: "Testing APIs & backends",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-snapshots",
      num: "I4",
      title: "Snapshot testing",
      short: "Snapshot testing",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-fixtures-data",
      num: "I5",
      title: "Fixtures & test data",
      short: "Fixtures & test data",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-mocking-network",
      num: "I6",
      title: "Mocking network requests",
      short: "Mocking network requests",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-databases",
      num: "I7",
      title: "Testing against a database",
      short: "Testing against a database",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-bdd",
      num: "I8",
      title: "Behavior-driven development",
      short: "BDD",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-flaky-tests",
      num: "I9",
      title: "Flaky tests",
      short: "Flaky tests",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "testing-e2e",
      num: "A1",
      title: "End-to-end testing",
      short: "End-to-end testing",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-visual-regression",
      num: "A2",
      title: "Visual regression testing",
      short: "Visual regression",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-contract",
      num: "A3",
      title: "Contract testing",
      short: "Contract testing",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-performance",
      num: "A4",
      title: "Performance testing",
      short: "Performance testing",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-accessibility",
      num: "A5",
      title: "Accessibility testing",
      short: "Accessibility testing",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-architecture-scale",
      num: "A6",
      title: "Test architecture at scale",
      short: "Architecture at scale",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-mutation",
      num: "A7",
      title: "Mutation testing",
      short: "Mutation testing",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "testing-strategy",
      num: "A8",
      title: "Test strategy",
      short: "Test strategy",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
