import type { NotesFile } from "./types";

export const typescriptNotes: NotesFile = {
  meta: {
    title: "TypeScript — the whole map",
    subtitle: "29 sections across three levels. The shelf is up — the notes aren't written yet.",
    lead: "Pick a level and you'll get these sections in the order that makes sense. Each one opens here the moment it's written; until then it just says so.",
    author: "Akshat",
    updated: "August 2026",
  },

  hero: { figure: "" },

  chapters: [
    {
      id: "ts-setup-compiler",
      num: "B1",
      title: "Setup & the compiler",
      short: "Setup & compiler",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-basic-types",
      num: "B2",
      title: "Basic types",
      short: "Basic types",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-functions",
      num: "B3",
      title: "Functions",
      short: "Functions",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-interfaces-aliases",
      num: "B4",
      title: "Interfaces & type aliases",
      short: "Interfaces & aliases",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-union-intersection",
      num: "B5",
      title: "Union & intersection types",
      short: "Union & intersection",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-enums-literals",
      num: "B6",
      title: "Enums & literal types",
      short: "Enums & literals",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-classes",
      num: "B7",
      title: "Classes in TypeScript",
      short: "Classes",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-dom-json",
      num: "B8",
      title: "Working with the DOM & JSON",
      short: "DOM & JSON",
      levels: ["beginner"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "ts-structural-typing",
      num: "I1",
      title: "Structural typing & inference in depth",
      short: "Structural typing",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-narrowing",
      num: "I2",
      title: "Narrowing",
      short: "Narrowing",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-runtime-validation",
      num: "I3",
      title: "Runtime validation with Zod",
      short: "Runtime validation",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-generics",
      num: "I4",
      title: "Generics",
      short: "Generics",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-utility-types",
      num: "I5",
      title: "Utility types",
      short: "Utility types",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-mapped-conditional",
      num: "I6",
      title: "Mapped & conditional types",
      short: "Mapped & conditional",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-modules-declarations",
      num: "I7",
      title: "Modules, namespaces & declaration files",
      short: "Modules & .d.ts",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-tsconfig-real-projects",
      num: "I8",
      title: "Configuring tsconfig for real projects",
      short: "tsconfig in depth",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-third-party-types",
      num: "I9",
      title: "Working with third-party types",
      short: "Third-party types",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-async-typing",
      num: "I10",
      title: "Typing async code",
      short: "Typing async code",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-testing-typed-code",
      num: "I11",
      title: "Testing typed code",
      short: "Testing typed code",
      levels: ["intermediate"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },

    {
      id: "ts-advanced-generics",
      num: "A1",
      title: "Advanced generics",
      short: "Advanced generics",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-conditional-recursive-types",
      num: "A2",
      title: "Conditional & recursive types",
      short: "Conditional & recursive types",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-type-level-programming",
      num: "A3",
      title: "Type-level programming",
      short: "Type-level programming",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-decorators",
      num: "A4",
      title: "Decorators & metadata",
      short: "Decorators & metadata",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-structural-vs-nominal",
      num: "A5",
      title: "Structural vs nominal typing tradeoffs",
      short: "Structural vs nominal",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-build-performance",
      num: "A6",
      title: "Type-checking performance",
      short: "Type-check performance",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-monorepo-setups",
      num: "A7",
      title: "Monorepo & multi-package setups",
      short: "Monorepo setups",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-migrating-js",
      num: "A8",
      title: "Migrating a JS codebase to TypeScript",
      short: "Migrating from JS",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-compiler-api",
      num: "A9",
      title: "The TypeScript compiler API",
      short: "Compiler API",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
    {
      id: "ts-fullstack-type-safety",
      num: "A10",
      title: "End-to-end type safety",
      short: "End-to-end type safety",
      levels: ["advanced"],
      practice: [],
      ready: false,
      subtitle: "",
      body: "",
    },
  ],
};
