import type { Exercise } from "../types";

// Component exercises: rendered in the sandbox iframe and tested through the DOM.
// React and its hooks are in scope, and so are render, screen, click, type and friends.
export const reactComponents: Exercise[] = [
  {
    id: "ex-comp-counter-step",
    chapter: "react-usestate",
    level: "beginner",
    kind: "component",
    title: "A counter with a step",
    brief: "<p>Build <code>App</code>: a counter that shows <code>Count: 0</code>, has an <b>Increment</b> and a <b>Decrement</b> button, and a number field labelled <b>Step</b> (starting at 1) that sets how much each click changes the count. <code>React</code>, <code>useState</code> and the other hooks are already in scope, and <b>Run</b> renders <code>App</code> in the preview.</p>",
    starter: "function App() {\n  // TODO: keep the count and the step in state\n  return (\n    <div>\n      <p>Count: 0</p>\n    </div>\n  );\n}\n",
    hints: [
      "Two pieces of state: count and step. The step field is a controlled input.",
      "An input's value is a string. Convert it with Number(e.target.value).",
      "Update the count from the previous one: setCount((c) => c + step).",
    ],
    solution: "function App() {\n  const [count, setCount] = useState(0);\n  const [step, setStep] = useState(1);\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <label>\n        Step <input type=\"number\" value={step} onChange={(e) => setStep(Number(e.target.value))} />\n      </label>\n      <button onClick={() => setCount((c) => c + step)}>Increment</button>\n      <button onClick={() => setCount((c) => c - step)}>Decrement</button>\n    </div>\n  );\n}\n",
    tests: [
      { name: "starts at zero", body: "render(<App />);\nassert.ok(screen.getByText(\"Count: 0\"));" },
      { name: "Increment adds one", body: "render(<App />);\nawait click(screen.getByRole(\"button\", { name: \"Increment\" }));\nassert.ok(screen.getByText(\"Count: 1\"));" },
      { name: "Decrement subtracts one and can go below zero", body: "render(<App />);\nawait click(screen.getByRole(\"button\", { name: \"Decrement\" }));\nassert.ok(screen.getByText(\"Count: -1\"));" },
      { name: "the step field starts at 1", body: "render(<App />);\nassert.equal(Number(screen.getByLabelText(\"Step\").value), 1);" },
      { name: "a bigger step changes each click by that much", body: "render(<App />);\nconst step = screen.getByLabelText(\"Step\");\nawait clear(step);\nawait type(step, \"5\");\nawait click(screen.getByRole(\"button\", { name: \"Increment\" }));\nassert.ok(screen.getByText(\"Count: 5\"));\nawait click(screen.getByRole(\"button\", { name: \"Decrement\" }));\nawait click(screen.getByRole(\"button\", { name: \"Decrement\" }));\nassert.ok(screen.getByText(\"Count: -5\"));" },
      { name: "the step field keeps its value after clicking", body: "render(<App />);\nconst step = screen.getByLabelText(\"Step\");\nawait clear(step);\nawait type(step, \"3\");\nawait click(screen.getByRole(\"button\", { name: \"Increment\" }));\nassert.equal(Number(step.value), 3);" },
      { name: "two counters do not share state", body: "render(<><App /><App /></>);\nconst [first] = screen.getAllByRole(\"button\", { name: \"Increment\" });\nawait click(first);\nawait click(first);\nconst counts = screen.getAllByText(/Count:/).map((el) => el.textContent);\nassert.deepEqual(counts, [\"Count: 2\", \"Count: 0\"]);" },
      { name: "many clicks add up", body: "render(<App />);\nconst inc = screen.getByRole(\"button\", { name: \"Increment\" });\nfor (let i = 0; i < 10; i++) await click(inc);\nassert.ok(screen.getByText(\"Count: 10\"));" },
    ],
  },
  {
    id: "ex-comp-zero-bug",
    chapter: "react-events-conditionals",
    level: "beginner",
    kind: "component",
    title: "Fix the stray zero",
    brief: "<p><code>Inbox</code> should show <code>You have N unread</code> only when there are messages. Right now an empty inbox prints a lone <b>0</b> on the page. Fix it without changing what the component shows for a non-empty inbox.</p>",
    starter: "function Inbox({ messages }) {\n  return (\n    <section>\n      <h2>Inbox</h2>\n      {messages.length && <p>You have {messages.length} unread</p>}\n    </section>\n  );\n}\n\nfunction App() {\n  return <Inbox messages={[]} />;\n}\n",
    hints: [
      "In JavaScript 0 && x is 0, and React renders the number 0.",
      "Make the condition a real boolean: messages.length > 0.",
    ],
    solution: "function Inbox({ messages }) {\n  return (\n    <section>\n      <h2>Inbox</h2>\n      {messages.length > 0 && <p>You have {messages.length} unread</p>}\n    </section>\n  );\n}\n\nfunction App() {\n  return <Inbox messages={[]} />;\n}\n",
    tests: [
      { name: "an empty inbox prints no stray zero", body: "const { container } = render(<Inbox messages={[]} />);\nassert.ok(!/0/.test(container.textContent), \"found text: \" + container.textContent);" },
      { name: "an empty inbox shows no unread line", body: "const { container } = render(<Inbox messages={[]} />);\nassert.equal(container.querySelectorAll(\"p\").length, 0);" },
      { name: "three messages", body: "render(<Inbox messages={[1, 2, 3]} />);\nassert.ok(screen.getByText(\"You have 3 unread\"));" },
      { name: "one message", body: "render(<Inbox messages={[\"a\"]} />);\nassert.ok(screen.getByText(\"You have 1 unread\"));" },
      { name: "twelve messages", body: "render(<Inbox messages={new Array(12).fill(0)} />);\nassert.ok(screen.getByText(\"You have 12 unread\"));" },
      { name: "the heading is always there", body: "render(<Inbox messages={[]} />);\nassert.ok(screen.getByRole(\"heading\", { name: \"Inbox\" }));" },
      { name: "going from three messages to none removes the line and leaves no zero", body: "const view = render(<Inbox messages={[1, 2, 3]} />);\nassert.ok(screen.getByText(\"You have 3 unread\"));\nview.rerender(<Inbox messages={[]} />);\nassert.equal(screen.queryByText(/unread/), null);\nassert.ok(!/0/.test(view.container.textContent));" },
      { name: "the count follows the messages", body: "const view = render(<Inbox messages={[1]} />);\nview.rerender(<Inbox messages={[1, 2, 3, 4, 5]} />);\nassert.ok(screen.getByText(\"You have 5 unread\"));" },
    ],
  },
  {
    id: "ex-comp-index-keys",
    chapter: "react-lists-keys",
    level: "beginner",
    kind: "component",
    title: "A list that keeps notes with their items",
    brief: "<p><code>App</code> shows three items, each with a note field and <b>Move up</b> / <b>Move down</b> buttons. Type a note, move the item, and the note ends up on the <em>wrong</em> item. Fix the key. Then disable <b>Move up</b> on the first item and <b>Move down</b> on the last.</p>",
    starter: "function App() {\n  const [items, setItems] = useState([\n    { id: 1, label: \"Apples\" },\n    { id: 2, label: \"Pears\" },\n    { id: 3, label: \"Plums\" },\n  ]);\n\n  function move(index, by) {\n    const next = items.slice();\n    const [item] = next.splice(index, 1);\n    next.splice(index + by, 0, item);\n    setItems(next);\n  }\n\n  return (\n    <ul>\n      {items.map((item, index) => (\n        <li key={index}>\n          <strong>{item.label}</strong>{\" \"}\n          <input aria-label={item.label + \" note\"} />{\" \"}\n          <button onClick={() => move(index, -1)}>Move up {item.label}</button>{\" \"}\n          <button onClick={() => move(index, 1)}>Move down {item.label}</button>\n        </li>\n      ))}\n    </ul>\n  );\n}\n",
    hints: [
      "React matches list items between renders by key. What does an index key say when the items swap places?",
      "Use the item's id as the key.",
      "disabled={index === 0} for Move up, and disabled={index === items.length - 1} for Move down.",
    ],
    solution: "function App() {\n  const [items, setItems] = useState([\n    { id: 1, label: \"Apples\" },\n    { id: 2, label: \"Pears\" },\n    { id: 3, label: \"Plums\" },\n  ]);\n\n  function move(index, by) {\n    const next = items.slice();\n    const [item] = next.splice(index, 1);\n    next.splice(index + by, 0, item);\n    setItems(next);\n  }\n\n  return (\n    <ul>\n      {items.map((item, index) => (\n        <li key={item.id}>\n          <strong>{item.label}</strong>{\" \"}\n          <input aria-label={item.label + \" note\"} />{\" \"}\n          <button disabled={index === 0} onClick={() => move(index, -1)}>Move up {item.label}</button>{\" \"}\n          <button disabled={index === items.length - 1} onClick={() => move(index, 1)}>Move down {item.label}</button>\n        </li>\n      ))}\n    </ul>\n  );\n}\n",
    tests: [
      { name: "three items in order", body: "render(<App />);\nconst labels = screen.getAllByRole(\"listitem\").map((li) => li.querySelector(\"strong\").textContent);\nassert.deepEqual(labels, [\"Apples\", \"Pears\", \"Plums\"]);" },
      { name: "moving an item down reorders the list", body: "render(<App />);\nawait click(screen.getByRole(\"button\", { name: \"Move down Apples\" }));\nconst labels = screen.getAllByRole(\"listitem\").map((li) => li.querySelector(\"strong\").textContent);\nassert.deepEqual(labels, [\"Pears\", \"Apples\", \"Plums\"]);" },
      { name: "a typed note stays with its item when it moves", body: "render(<App />);\nawait type(screen.getByLabelText(\"Apples note\"), \"hello\");\nawait click(screen.getByRole(\"button\", { name: \"Move down Apples\" }));\nassert.equal(screen.getByLabelText(\"Apples note\").value, \"hello\");\nassert.equal(screen.getByLabelText(\"Pears note\").value, \"\");" },
      { name: "each item keeps its own note through several moves", body: "render(<App />);\nawait type(screen.getByLabelText(\"Apples note\"), \"a\");\nawait type(screen.getByLabelText(\"Pears note\"), \"p\");\nawait type(screen.getByLabelText(\"Plums note\"), \"m\");\nawait click(screen.getByRole(\"button\", { name: \"Move up Plums\" }));\nawait click(screen.getByRole(\"button\", { name: \"Move up Plums\" }));\nassert.equal(screen.getByLabelText(\"Apples note\").value, \"a\");\nassert.equal(screen.getByLabelText(\"Pears note\").value, \"p\");\nassert.equal(screen.getByLabelText(\"Plums note\").value, \"m\");\nconst labels = screen.getAllByRole(\"listitem\").map((li) => li.querySelector(\"strong\").textContent);\nassert.deepEqual(labels, [\"Plums\", \"Apples\", \"Pears\"]);" },
      { name: "Move up is disabled on the first item", body: "render(<App />);\nassert.equal(screen.getByRole(\"button\", { name: \"Move up Apples\" }).disabled, true);\nassert.equal(screen.getByRole(\"button\", { name: \"Move up Pears\" }).disabled, false);" },
      { name: "Move down is disabled on the last item", body: "render(<App />);\nassert.equal(screen.getByRole(\"button\", { name: \"Move down Plums\" }).disabled, true);\nassert.equal(screen.getByRole(\"button\", { name: \"Move down Pears\" }).disabled, false);" },
      { name: "the disabled buttons follow the items after a move", body: "render(<App />);\nawait click(screen.getByRole(\"button\", { name: \"Move down Apples\" }));\nassert.equal(screen.getByRole(\"button\", { name: \"Move up Pears\" }).disabled, true);\nassert.equal(screen.getByRole(\"button\", { name: \"Move up Apples\" }).disabled, false);" },
      { name: "there are always exactly three items", body: "render(<App />);\nawait click(screen.getByRole(\"button\", { name: \"Move up Plums\" }));\nassert.equal(screen.getAllByRole(\"listitem\").length, 3);" },
    ],
  },
  {
    id: "ex-comp-signup-form",
    chapter: "react-forms",
    level: "beginner",
    kind: "component",
    title: "A signup form that validates on submit",
    brief: "<p>Build <code>App</code>: a form with fields labelled <b>Email</b> and <b>Password</b> (a password input) and a <b>Sign up</b> button. Nothing is validated while typing. On submit, show a paragraph with <code>role=\"alert\"</code> for each failing field: <code>Enter a valid email</code> if the email has no <code>@</code>, and <code>Password must be at least 8 characters</code> if the password is shorter. If both are fine, replace the form with <code>Welcome, EMAIL!</code>.</p>",
    starter: "function App() {\n  // TODO: controlled fields, validation on submit\n  return (\n    <form>\n      <label>\n        Email <input />\n      </label>\n      <label>\n        Password <input type=\"password\" />\n      </label>\n      <button>Sign up</button>\n    </form>\n  );\n}\n",
    hints: [
      "Keep email, password and errors in state. The inputs are controlled: value + onChange.",
      "onSubmit gets an event; call e.preventDefault() first.",
      "Build an errors object on submit; if it is empty, set a submitted flag and show the welcome text.",
    ],
    solution: "function App() {\n  const [email, setEmail] = useState(\"\");\n  const [password, setPassword] = useState(\"\");\n  const [errors, setErrors] = useState({});\n  const [done, setDone] = useState(false);\n\n  function submit(e) {\n    e.preventDefault();\n    const next = {};\n    if (!email.includes(\"@\")) next.email = \"Enter a valid email\";\n    if (password.length < 8) next.password = \"Password must be at least 8 characters\";\n    setErrors(next);\n    if (Object.keys(next).length === 0) setDone(true);\n  }\n\n  if (done) return <p>Welcome, {email}!</p>;\n\n  return (\n    <form onSubmit={submit} noValidate>\n      <label>\n        Email <input value={email} onChange={(e) => setEmail(e.target.value)} />\n      </label>\n      {errors.email && <p role=\"alert\">{errors.email}</p>}\n      <label>\n        Password <input type=\"password\" value={password} onChange={(e) => setPassword(e.target.value)} />\n      </label>\n      {errors.password && <p role=\"alert\">{errors.password}</p>}\n      <button>Sign up</button>\n    </form>\n  );\n}\n",
    tests: [
      { name: "no errors before anything is submitted", body: "render(<App />);\nassert.equal(screen.queryByRole(\"alert\"), null);" },
      { name: "typing does not validate", body: "render(<App />);\nawait type(screen.getByLabelText(\"Email\"), \"nope\");\nassert.equal(screen.queryByRole(\"alert\"), null);" },
      { name: "an empty submit shows both errors", body: "render(<App />);\nawait click(screen.getByRole(\"button\", { name: \"Sign up\" }));\nconst alerts = screen.getAllByRole(\"alert\").map((a) => a.textContent);\nassert.deepEqual(alerts, [\"Enter a valid email\", \"Password must be at least 8 characters\"]);" },
      { name: "a bad email alone", body: "render(<App />);\nawait type(screen.getByLabelText(\"Email\"), \"nope\");\nawait type(screen.getByLabelText(\"Password\"), \"longenough\");\nawait click(screen.getByRole(\"button\", { name: \"Sign up\" }));\nassert.deepEqual(screen.getAllByRole(\"alert\").map((a) => a.textContent), [\"Enter a valid email\"]);" },
      { name: "a short password alone", body: "render(<App />);\nawait type(screen.getByLabelText(\"Email\"), \"a@b.com\");\nawait type(screen.getByLabelText(\"Password\"), \"short\");\nawait click(screen.getByRole(\"button\", { name: \"Sign up\" }));\nassert.deepEqual(screen.getAllByRole(\"alert\").map((a) => a.textContent), [\"Password must be at least 8 characters\"]);" },
      { name: "seven characters is too short, eight is enough", body: "render(<App />);\nawait type(screen.getByLabelText(\"Email\"), \"a@b.com\");\nawait type(screen.getByLabelText(\"Password\"), \"1234567\");\nawait click(screen.getByRole(\"button\", { name: \"Sign up\" }));\nassert.ok(screen.getByRole(\"alert\"));\nawait type(screen.getByLabelText(\"Password\"), \"8\");\nawait click(screen.getByRole(\"button\", { name: \"Sign up\" }));\nassert.ok(screen.getByText(\"Welcome, a@b.com!\"));" },
      { name: "valid details replace the form with a welcome", body: "render(<App />);\nawait type(screen.getByLabelText(\"Email\"), \"ana@example.com\");\nawait type(screen.getByLabelText(\"Password\"), \"correct horse\");\nawait click(screen.getByRole(\"button\", { name: \"Sign up\" }));\nassert.ok(screen.getByText(\"Welcome, ana@example.com!\"));\nassert.equal(screen.queryByRole(\"button\", { name: \"Sign up\" }), null);" },
      { name: "errors clear once the fields are fixed and resubmitted", body: "render(<App />);\nawait click(screen.getByRole(\"button\", { name: \"Sign up\" }));\nassert.equal(screen.getAllByRole(\"alert\").length, 2);\nawait type(screen.getByLabelText(\"Email\"), \"a@b.com\");\nawait type(screen.getByLabelText(\"Password\"), \"12345678\");\nawait click(screen.getByRole(\"button\", { name: \"Sign up\" }));\nassert.equal(screen.queryByRole(\"alert\"), null);" },
      { name: "the password field is a password input", body: "render(<App />);\nassert.equal(screen.getByLabelText(\"Password\").type, \"password\");" },
    ],
  },
  {
    id: "ex-comp-filter-list",
    chapter: "react-thinking",
    level: "beginner",
    kind: "component",
    title: "Derive the visible list, don't store it",
    brief: "<p>Build <code>ProductList({ products })</code>. It shows a text field labelled <b>Search</b>, a checkbox labelled <b>In stock only</b> and one list item per matching product name. Matching ignores case. When nothing matches, show <code>No products match</code> instead of the list. The filtered list must be <em>computed during render</em>, not kept in state.</p>",
    starter: "function ProductList({ products }) {\n  // TODO\n  return (\n    <div>\n      <ul>\n        {products.map((p) => (\n          <li key={p.name}>{p.name}</li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nfunction App() {\n  return (\n    <ProductList\n      products={[\n        { name: \"Football\", stocked: true },\n        { name: \"Baseball\", stocked: false },\n        { name: \"Basketball\", stocked: true },\n      ]}\n    />\n  );\n}\n",
    hints: [
      "State needs only two values: the query and the checkbox. Everything else is derived.",
      "products.filter(...) inside the component body runs on every render, which is exactly what you want.",
      "Case-insensitive: compare toLowerCase() on both sides.",
    ],
    solution: "function ProductList({ products }) {\n  const [query, setQuery] = useState(\"\");\n  const [inStockOnly, setInStockOnly] = useState(false);\n  const visible = products.filter(\n    (p) => p.name.toLowerCase().includes(query.toLowerCase()) && (!inStockOnly || p.stocked)\n  );\n  return (\n    <div>\n      <label>\n        Search <input value={query} onChange={(e) => setQuery(e.target.value)} />\n      </label>\n      <label>\n        <input type=\"checkbox\" checked={inStockOnly} onChange={(e) => setInStockOnly(e.target.checked)} /> In stock only\n      </label>\n      {visible.length === 0 ? (\n        <p>No products match</p>\n      ) : (\n        <ul>\n          {visible.map((p) => (\n            <li key={p.name}>{p.name}</li>\n          ))}\n        </ul>\n      )}\n    </div>\n  );\n}\n\nfunction App() {\n  return (\n    <ProductList\n      products={[\n        { name: \"Football\", stocked: true },\n        { name: \"Baseball\", stocked: false },\n        { name: \"Basketball\", stocked: true },\n      ]}\n    />\n  );\n}\n",
    tests: [
      { name: "everything is listed at first", body: "render(<App />);\nassert.equal(screen.getAllByRole(\"listitem\").length, 3);" },
      { name: "typing narrows the list", body: "render(<App />);\nconst search = screen.getByLabelText(\"Search\");\nawait type(search, \"ball\");\nassert.equal(screen.getAllByRole(\"listitem\").length, 3);\nawait clear(search);\nawait type(search, \"bas\");\nassert.deepEqual(screen.getAllByRole(\"listitem\").map((li) => li.textContent), [\"Baseball\", \"Basketball\"]);" },
      { name: "matching ignores case", body: "render(<App />);\nawait type(screen.getByLabelText(\"Search\"), \"FOOT\");\nassert.deepEqual(screen.getAllByRole(\"listitem\").map((li) => li.textContent), [\"Football\"]);" },
      { name: "in stock only hides what is out of stock", body: "render(<App />);\nawait click(screen.getByLabelText(\"In stock only\"));\nassert.deepEqual(screen.getAllByRole(\"listitem\").map((li) => li.textContent), [\"Football\", \"Basketball\"]);" },
      { name: "the query and the checkbox combine", body: "render(<App />);\nawait type(screen.getByLabelText(\"Search\"), \"bas\");\nawait click(screen.getByLabelText(\"In stock only\"));\nassert.deepEqual(screen.getAllByRole(\"listitem\").map((li) => li.textContent), [\"Basketball\"]);" },
      { name: "no match shows the message instead of an empty list", body: "render(<App />);\nawait type(screen.getByLabelText(\"Search\"), \"zzz\");\nassert.ok(screen.getByText(\"No products match\"));\nassert.equal(screen.queryByRole(\"list\"), null);" },
      { name: "clearing the query brings everything back", body: "render(<App />);\nconst search = screen.getByLabelText(\"Search\");\nawait type(search, \"zzz\");\nawait clear(search);\nassert.equal(screen.getAllByRole(\"listitem\").length, 3);\nassert.equal(screen.queryByText(\"No products match\"), null);" },
      { name: "it filters whatever products it is given", body: "render(<ProductList products={[{ name: \"Kettle\", stocked: true }]} />);\nassert.deepEqual(screen.getAllByRole(\"listitem\").map((li) => li.textContent), [\"Kettle\"]);\nawait type(screen.getByLabelText(\"Search\"), \"x\");\nassert.ok(screen.getByText(\"No products match\"));" },
    ],
  },
  {
    id: "ex-comp-synced-inputs",
    chapter: "react-lifting-styling",
    level: "beginner",
    kind: "component",
    title: "Two inputs, one source of truth",
    brief: "<p>Build <code>App</code>: a <b>Celsius</b> field and a <b>Fahrenheit</b> field that always agree. Typing in either updates the other, rounded to one decimal place (<code>37</code> °C is <code>98.6</code> °F). Clearing one clears the other. Keep the value in <em>one</em> place: lift the state instead of syncing two copies.</p>",
    starter: "function App() {\n  // TODO: one shared state, two views of it\n  return (\n    <div>\n      <label>\n        Celsius <input />\n      </label>\n      <label>\n        Fahrenheit <input />\n      </label>\n    </div>\n  );\n}\n",
    hints: [
      "Store what the user typed and which field they typed it in: { value, scale }.",
      "Convert for display: the field they did not touch shows the converted number, rounded.",
      "F = C * 9 / 5 + 32 and C = (F - 32) * 5 / 9. Round with Math.round(x * 10) / 10.",
    ],
    solution: "const toF = (c) => (c * 9) / 5 + 32;\nconst toC = (f) => ((f - 32) * 5) / 9;\nconst round = (n) => String(Math.round(n * 10) / 10);\n\nfunction App() {\n  const [state, setState] = useState({ value: \"\", scale: \"c\" });\n  const number = parseFloat(state.value);\n  const celsius = state.scale === \"c\" ? state.value : Number.isNaN(number) ? \"\" : round(toC(number));\n  const fahrenheit = state.scale === \"f\" ? state.value : Number.isNaN(number) ? \"\" : round(toF(number));\n  return (\n    <div>\n      <label>\n        Celsius <input value={celsius} onChange={(e) => setState({ value: e.target.value, scale: \"c\" })} />\n      </label>\n      <label>\n        Fahrenheit <input value={fahrenheit} onChange={(e) => setState({ value: e.target.value, scale: \"f\" })} />\n      </label>\n    </div>\n  );\n}\n",
    tests: [
      { name: "both fields start empty", body: "render(<App />);\nassert.equal(screen.getByLabelText(\"Celsius\").value, \"\");\nassert.equal(screen.getByLabelText(\"Fahrenheit\").value, \"\");" },
      { name: "typing Celsius fills Fahrenheit", body: "render(<App />);\nawait type(screen.getByLabelText(\"Celsius\"), \"100\");\nassert.equal(screen.getByLabelText(\"Fahrenheit\").value, \"212\");" },
      { name: "typing Fahrenheit fills Celsius", body: "render(<App />);\nawait type(screen.getByLabelText(\"Fahrenheit\"), \"32\");\nassert.equal(screen.getByLabelText(\"Celsius\").value, \"0\");" },
      { name: "the field being typed in keeps exactly what was typed", body: "render(<App />);\nawait type(screen.getByLabelText(\"Celsius\"), \"37\");\nassert.equal(screen.getByLabelText(\"Celsius\").value, \"37\");" },
      { name: "results are rounded to one decimal", body: "render(<App />);\nawait type(screen.getByLabelText(\"Celsius\"), \"37\");\nassert.equal(screen.getByLabelText(\"Fahrenheit\").value, \"98.6\");" },
      { name: "negative temperatures", body: "render(<App />);\nawait type(screen.getByLabelText(\"Celsius\"), \"-40\");\nassert.equal(screen.getByLabelText(\"Fahrenheit\").value, \"-40\");" },
      { name: "clearing one field clears the other", body: "render(<App />);\nconst c = screen.getByLabelText(\"Celsius\");\nawait type(c, \"20\");\nassert.equal(screen.getByLabelText(\"Fahrenheit\").value, \"68\");\nawait clear(c);\nassert.equal(screen.getByLabelText(\"Fahrenheit\").value, \"\");" },
      { name: "switching between the two fields keeps them in step", body: "render(<App />);\nawait type(screen.getByLabelText(\"Celsius\"), \"10\");\nconst f = screen.getByLabelText(\"Fahrenheit\");\nawait clear(f);\nawait type(f, \"212\");\nassert.equal(screen.getByLabelText(\"Celsius\").value, \"100\");" },
    ],
  },
  {
    id: "ex-comp-props-badge",
    chapter: "react-props",
    level: "beginner",
    kind: "component",
    title: "A Badge with sensible defaults",
    brief: "<p>Build <code>Badge({ label, tone = \"info\", children, className, ...rest })</code>. It renders one <code>&lt;span&gt;</code> whose class list is <code>badge badge--TONE</code> followed by any extra <code>className</code>, containing the <code>label</code> and then the <code>children</code>. Every other prop (such as <code>title</code> or <code>data-testid</code>) goes onto the span.</p>",
    starter: "function Badge(props) {\n  // TODO\n  return <span>{props.label}</span>;\n}\n\nfunction App() {\n  return <Badge label=\"New\" tone=\"success\" />;\n}\n",
    hints: [
      "Destructure with defaults in the parameter list.",
      "Build the class string: [\"badge\", \"badge--\" + tone, className].filter(Boolean).join(\" \").",
      "{...rest} spreads the remaining props onto the span.",
    ],
    solution: "function Badge({ label, tone = \"info\", children, className, ...rest }) {\n  const classes = [\"badge\", \"badge--\" + tone, className].filter(Boolean).join(\" \");\n  return (\n    <span className={classes} {...rest}>\n      {label}\n      {children}\n    </span>\n  );\n}\n\nfunction App() {\n  return <Badge label=\"New\" tone=\"success\" />;\n}\n",
    tests: [
      { name: "it renders the label", body: "render(<Badge label=\"New\" />);\nassert.ok(screen.getByText(\"New\"));" },
      { name: "the tone defaults to info", body: "const { container } = render(<Badge label=\"x\" />);\nassert.equal(container.querySelector(\"span\").className, \"badge badge--info\");" },
      { name: "a given tone is used", body: "const { container } = render(<Badge label=\"x\" tone=\"warn\" />);\nassert.equal(container.querySelector(\"span\").className, \"badge badge--warn\");" },
      { name: "an extra className is appended", body: "const { container } = render(<Badge label=\"x\" tone=\"success\" className=\"big\" />);\nassert.equal(container.querySelector(\"span\").className, \"badge badge--success big\");" },
      { name: "children come after the label", body: "const { container } = render(<Badge label=\"Beta\"> (v2)</Badge>);\nassert.equal(container.querySelector(\"span\").textContent, \"Beta (v2)\");" },
      { name: "other props land on the span", body: "render(<Badge label=\"x\" title=\"hint\" data-testid=\"b\" />);\nconst el = screen.getByTestId(\"b\");\nassert.equal(el.getAttribute(\"title\"), \"hint\");\nassert.equal(el.tagName, \"SPAN\");" },
      { name: "there is exactly one element", body: "const { container } = render(<Badge label=\"x\" />);\nassert.equal(container.children.length, 1);\nassert.equal(container.querySelectorAll(\"*\").length, 1);" },
      { name: "tone is not leaked as an attribute", body: "const { container } = render(<Badge label=\"x\" tone=\"warn\" />);\nassert.equal(container.querySelector(\"span\").hasAttribute(\"tone\"), false);" },
    ],
  },
  {
    id: "ex-comp-disclosure",
    chapter: "react-events-conditionals",
    level: "beginner",
    kind: "component",
    title: "An accessible show/hide section",
    brief: "<p>Build <code>Disclosure({ title, children, defaultOpen = false })</code>: a button showing the <code>title</code> that toggles a panel. The button carries <code>aria-expanded</code> (<code>\"true\"</code> or <code>\"false\"</code>) and <code>aria-controls</code> pointing at the panel's id (use <code>useId</code>). The panel has <code>role=\"region\"</code> and is <b>not rendered</b> while closed. Each Disclosure keeps its own state.</p>",
    starter: "function Disclosure({ title, children }) {\n  // TODO\n  return (\n    <div>\n      <button>{title}</button>\n    </div>\n  );\n}\n\nfunction App() {\n  return <Disclosure title=\"More details\">Hidden until you ask.</Disclosure>;\n}\n",
    hints: [
      "One boolean of state: open.",
      "aria-expanded={open} works: React writes it as the string \"true\" or \"false\".",
      "const id = useId(); the button gets aria-controls={id} and the panel gets id={id}.",
    ],
    solution: "function Disclosure({ title, children, defaultOpen = false }) {\n  const [open, setOpen] = useState(defaultOpen);\n  const id = useId();\n  return (\n    <div>\n      <button aria-expanded={open} aria-controls={id} onClick={() => setOpen((o) => !o)}>\n        {title}\n      </button>\n      {open && (\n        <div id={id} role=\"region\">\n          {children}\n        </div>\n      )}\n    </div>\n  );\n}\n\nfunction App() {\n  return <Disclosure title=\"More details\">Hidden until you ask.</Disclosure>;\n}\n",
    tests: [
      { name: "closed by default: the content is not in the page", body: "render(<Disclosure title=\"Details\">Secret</Disclosure>);\nassert.equal(screen.queryByText(\"Secret\"), null);\nassert.equal(screen.queryByRole(\"region\"), null);" },
      { name: "the button is named after the title", body: "render(<Disclosure title=\"Details\">Secret</Disclosure>);\nassert.ok(screen.getByRole(\"button\", { name: \"Details\" }));" },
      { name: "aria-expanded starts false", body: "render(<Disclosure title=\"Details\">Secret</Disclosure>);\nassert.equal(screen.getByRole(\"button\").getAttribute(\"aria-expanded\"), \"false\");" },
      { name: "clicking opens it", body: "render(<Disclosure title=\"Details\">Secret</Disclosure>);\nawait click(screen.getByRole(\"button\"));\nassert.ok(screen.getByText(\"Secret\"));\nassert.equal(screen.getByRole(\"button\").getAttribute(\"aria-expanded\"), \"true\");" },
      { name: "clicking again closes it", body: "render(<Disclosure title=\"Details\">Secret</Disclosure>);\nconst b = screen.getByRole(\"button\");\nawait click(b);\nawait click(b);\nassert.equal(screen.queryByText(\"Secret\"), null);\nassert.equal(b.getAttribute(\"aria-expanded\"), \"false\");" },
      { name: "aria-controls points at the panel", body: "render(<Disclosure title=\"Details\" defaultOpen>Secret</Disclosure>);\nconst panel = screen.getByRole(\"region\");\nassert.ok(panel.id);\nassert.equal(screen.getByRole(\"button\").getAttribute(\"aria-controls\"), panel.id);" },
      { name: "defaultOpen starts it open", body: "render(<Disclosure title=\"Details\" defaultOpen>Secret</Disclosure>);\nassert.ok(screen.getByText(\"Secret\"));\nassert.equal(screen.getByRole(\"button\").getAttribute(\"aria-expanded\"), \"true\");" },
      { name: "two disclosures are independent and have different ids", body: "render(<><Disclosure title=\"A\" defaultOpen>one</Disclosure><Disclosure title=\"B\" defaultOpen>two</Disclosure></>);\nconst [a, b] = screen.getAllByRole(\"region\");\nassert.notEqual(a.id, b.id);\nawait click(screen.getByRole(\"button\", { name: \"A\" }));\nassert.equal(screen.queryByText(\"one\"), null);\nassert.ok(screen.getByText(\"two\"));" },
    ],
  },
  {
    id: "ex-comp-star-rating",
    chapter: "react-events-conditionals",
    level: "beginner",
    kind: "component",
    title: "A star rating with hover preview",
    brief: "<p>Build <code>StarRating({ max = 5, defaultValue = 0, onChange })</code>: <code>max</code> buttons labelled <code>1 star</code>, <code>2 stars</code>, and so on. A filled star shows <code>★</code>, an empty one <code>☆</code>. Clicking a star sets the rating and calls <code>onChange(value)</code>; clicking the current rating again clears it to 0. While the pointer is over a star, the display previews that rating; leaving restores the real one. Each button has <code>aria-pressed</code> when it is at or below the rating.</p>",
    starter: "function StarRating({ max = 5, defaultValue = 0, onChange }) {\n  // TODO\n  return <div>{\"\\u2606\".repeat(max)}</div>;\n}\n\nfunction App() {\n  return <StarRating />;\n}\n",
    hints: [
      "Two pieces of state: the chosen value and the hovered value (or null).",
      "Display value = hovered ?? value.",
      "onMouseEnter sets the hover, onMouseLeave clears it.",
    ],
    solution: "function StarRating({ max = 5, defaultValue = 0, onChange }) {\n  const [value, setValue] = useState(defaultValue);\n  const [hover, setHover] = useState(null);\n  const shown = hover ?? value;\n\n  function choose(n) {\n    const next = n === value ? 0 : n;\n    setValue(next);\n    if (onChange) onChange(next);\n  }\n\n  return (\n    <div>\n      {Array.from({ length: max }, (_, i) => i + 1).map((n) => (\n        <button\n          key={n}\n          aria-label={n + (n === 1 ? \" star\" : \" stars\")}\n          aria-pressed={n <= value}\n          onClick={() => choose(n)}\n          onMouseEnter={() => setHover(n)}\n          onMouseLeave={() => setHover(null)}\n        >\n          {n <= shown ? \"\\u2605\" : \"\\u2606\"}\n        </button>\n      ))}\n    </div>\n  );\n}\n\nfunction App() {\n  return <StarRating />;\n}\n",
    tests: [
      { name: "five empty stars by default", body: "const { container } = render(<StarRating />);\nassert.equal(screen.getAllByRole(\"button\").length, 5);\nassert.equal(container.textContent, \"\\u2606\\u2606\\u2606\\u2606\\u2606\");" },
      { name: "the buttons are labelled", body: "render(<StarRating />);\nassert.ok(screen.getByRole(\"button\", { name: \"1 star\" }));\nassert.ok(screen.getByRole(\"button\", { name: \"3 stars\" }));" },
      { name: "clicking a star fills up to it", body: "const { container } = render(<StarRating />);\nawait click(screen.getByRole(\"button\", { name: \"3 stars\" }));\nassert.equal(container.textContent, \"\\u2605\\u2605\\u2605\\u2606\\u2606\");" },
      { name: "onChange is called with the new value", body: "const seen = [];\nrender(<StarRating onChange={(v) => seen.push(v)} />);\nawait click(screen.getByRole(\"button\", { name: \"4 stars\" }));\nawait click(screen.getByRole(\"button\", { name: \"2 stars\" }));\nassert.deepEqual(seen, [4, 2]);" },
      { name: "clicking the current rating clears it", body: "const seen = [];\nconst { container } = render(<StarRating defaultValue={2} onChange={(v) => seen.push(v)} />);\nawait click(screen.getByRole(\"button\", { name: \"2 stars\" }));\nassert.equal(container.textContent, \"\\u2606\\u2606\\u2606\\u2606\\u2606\");\nassert.deepEqual(seen, [0]);" },
      { name: "hovering previews a rating", body: "const { container } = render(<StarRating defaultValue={1} />);\nawait hover(screen.getByRole(\"button\", { name: \"4 stars\" }));\nassert.equal(container.textContent, \"\\u2605\\u2605\\u2605\\u2605\\u2606\");" },
      { name: "leaving restores the real rating", body: "const { container } = render(<StarRating defaultValue={1} />);\nconst star = screen.getByRole(\"button\", { name: \"4 stars\" });\nawait hover(star);\nawait unhover(star);\nassert.equal(container.textContent, \"\\u2605\\u2606\\u2606\\u2606\\u2606\");" },
      { name: "aria-pressed follows the rating, not the hover", body: "render(<StarRating defaultValue={2} />);\nawait hover(screen.getByRole(\"button\", { name: \"5 stars\" }));\nassert.equal(screen.getByRole(\"button\", { name: \"2 stars\" }).getAttribute(\"aria-pressed\"), \"true\");\nassert.equal(screen.getByRole(\"button\", { name: \"3 stars\" }).getAttribute(\"aria-pressed\"), \"false\");" },
      { name: "max controls how many stars there are", body: "render(<StarRating max={3} />);\nassert.equal(screen.getAllByRole(\"button\").length, 3);" },
    ],
  },
  {
    id: "ex-comp-effect-loop",
    chapter: "react-effects-depth",
    level: "intermediate",
    kind: "component",
    title: "Stop the effect that never stops",
    brief: "<p><code>Results</code> filters a list by <code>query</code>, but it keeps re-rendering forever. The render counter at the top makes it visible. Fix it so the component renders a handful of times at most. (There is more than one fix; the best one removes the effect entirely.)</p>",
    starter: "const ALL = [\"apple\", \"banana\", \"cherry\", \"blueberry\"];\nlet renders = 0;\n\nfunction Results({ query }) {\n  renders++;\n  const [items, setItems] = useState([]);\n\n  useEffect(() => {\n    setItems(ALL.filter((x) => x.includes(query)));\n  });\n\n  return (\n    <ul>\n      {items.map((i) => (\n        <li key={i}>{i}</li>\n      ))}\n    </ul>\n  );\n}\n\nfunction App() {\n  return <Results query=\"b\" />;\n}\n",
    hints: [
      "An effect with no dependency array runs after every render. Setting state inside it renders again.",
      "Does this need to be state at all? The list can be computed from the query during render.",
      "If you keep the effect, give it [query] as dependencies.",
    ],
    solution: "const ALL = [\"apple\", \"banana\", \"cherry\", \"blueberry\"];\nlet renders = 0;\n\nfunction Results({ query }) {\n  renders++;\n  const items = ALL.filter((x) => x.includes(query));\n  return (\n    <ul>\n      {items.map((i) => (\n        <li key={i}>{i}</li>\n      ))}\n    </ul>\n  );\n}\n\nfunction App() {\n  return <Results query=\"b\" />;\n}\n",
    tests: [
      { name: "it lists everything for an empty query", body: "renders = 0;\nrender(<Results query=\"\" />);\nawait sleep(30);\nassert.deepEqual(screen.getAllByRole(\"listitem\").map((li) => li.textContent), [\"apple\", \"banana\", \"cherry\", \"blueberry\"]);" },
      { name: "it filters by the query", body: "renders = 0;\nrender(<Results query=\"b\" />);\nawait sleep(30);\nassert.deepEqual(screen.getAllByRole(\"listitem\").map((li) => li.textContent), [\"banana\", \"blueberry\"]);" },
      { name: "it does not render forever", body: "renders = 0;\nrender(<Results query=\"b\" />);\nawait sleep(150);\nassert.ok(renders <= 4, \"rendered \" + renders + \" times\");" },
      { name: "a new query updates the list", body: "renders = 0;\nconst view = render(<Results query=\"a\" />);\nawait sleep(30);\nview.rerender(<Results query=\"che\" />);\nawait sleep(30);\nassert.deepEqual(screen.getAllByRole(\"listitem\").map((li) => li.textContent), [\"cherry\"]);" },
      { name: "changing the query renders a bounded number of times", body: "renders = 0;\nconst view = render(<Results query=\"a\" />);\nawait sleep(30);\nconst before = renders;\nview.rerender(<Results query=\"b\" />);\nawait sleep(150);\nassert.ok(renders - before <= 3, \"rendered \" + (renders - before) + \" more times\");" },
      { name: "no match gives an empty list", body: "renders = 0;\nrender(<Results query=\"zzz\" />);\nawait sleep(30);\nassert.equal(screen.queryAllByRole(\"listitem\").length, 0);" },
      { name: "many rerenders stay stable", body: "renders = 0;\nconst view = render(<Results query=\"a\" />);\nfor (let i = 0; i < 5; i++) { view.rerender(<Results query={i % 2 ? \"a\" : \"e\"} />); await sleep(10); }\nawait sleep(100);\nassert.ok(renders <= 20, \"rendered \" + renders + \" times\");" },
      { name: "unmounting stops everything", body: "renders = 0;\nconst view = render(<Results query=\"b\" />);\nawait sleep(20);\nview.unmount();\nconst after = renders;\nawait sleep(100);\nassert.equal(renders, after);" },
    ],
  },
  {
    id: "ex-comp-stale-interval",
    chapter: "react-effects-depth",
    level: "intermediate",
    kind: "component",
    title: "A ticker that actually ticks",
    brief: "<p><code>Ticker</code> should add one every 20 milliseconds, but it shows <code>Ticks: 1</code> and stops. It is the stale closure bug: the interval callback captured the first render's <code>count</code>. Fix it, and keep exactly <b>one</b> interval running that is cleared when the component unmounts.</p>",
    starter: "function Ticker() {\n  const [count, setCount] = useState(0);\n\n  useEffect(() => {\n    const id = setInterval(() => setCount(count + 1), 20);\n    return () => clearInterval(id);\n  }, []);\n\n  return <p>Ticks: {count}</p>;\n}\n\nfunction App() {\n  return <Ticker />;\n}\n",
    hints: [
      "The effect runs once, so count inside the callback is always 0.",
      "setCount accepts a function that receives the latest value.",
      "Keep the empty dependency array: you want one interval, not one per tick.",
    ],
    solution: "function Ticker() {\n  const [count, setCount] = useState(0);\n\n  useEffect(() => {\n    const id = setInterval(() => setCount((c) => c + 1), 20);\n    return () => clearInterval(id);\n  }, []);\n\n  return <p>Ticks: {count}</p>;\n}\n\nfunction App() {\n  return <Ticker />;\n}\n",
    tests: [
      { name: "it starts at zero", body: "render(<Ticker />);\nassert.ok(screen.getByText(\"Ticks: 0\"));" },
      { name: "it counts past one", body: "render(<Ticker />);\nawait waitFor(() => assert.ok(Number(screen.getByText(/Ticks:/).textContent.replace(/\\D/g, \"\")) >= 3));" },
      { name: "it keeps counting steadily", body: "render(<Ticker />);\nawait sleep(250);\nconst n = Number(screen.getByText(/Ticks:/).textContent.replace(/\\D/g, \"\"));\nassert.ok(n >= 5, \"only \" + n + \" ticks in 250ms\");" },
      { name: "only one interval is created", body: "const created = [];\nconst original = window.setInterval;\nwindow.setInterval = (...args) => { const id = original(...args); created.push(id); return id; };\ntry {\n  render(<Ticker />);\n  await sleep(150);\n} finally {\n  window.setInterval = original;\n}\nassert.equal(created.length, 1);" },
      { name: "the interval is cleared on unmount", body: "const created = [];\nconst cleared = [];\nconst oSet = window.setInterval;\nconst oClear = window.clearInterval;\nwindow.setInterval = (...a) => { const id = oSet(...a); created.push(id); return id; };\nwindow.clearInterval = (id) => { cleared.push(id); return oClear(id); };\ntry {\n  const view = render(<Ticker />);\n  await sleep(50);\n  view.unmount();\n} finally {\n  window.setInterval = oSet;\n  window.clearInterval = oClear;\n}\nassert.deepEqual(cleared, created);" },
      { name: "two tickers count independently", body: "render(<><Ticker /><Ticker /></>);\nawait sleep(120);\nconst counts = screen.getAllByText(/Ticks:/).map((el) => Number(el.textContent.replace(/\\D/g, \"\")));\nassert.ok(counts.every((c) => c >= 2), counts.join());" },
      { name: "the count never goes backwards", body: "render(<Ticker />);\nlet last = 0;\nfor (let i = 0; i < 8; i++) {\n  await sleep(30);\n  const n = Number(screen.getByText(/Ticks:/).textContent.replace(/\\D/g, \"\"));\n  assert.ok(n >= last);\n  last = n;\n}\nassert.ok(last >= 4);" },
    ],
  },
  {
    id: "ex-comp-autofocus",
    chapter: "react-useref",
    level: "intermediate",
    kind: "component",
    title: "Focus the box, and give focus back",
    brief: "<p>Build <code>SearchBox</code>: a text field labelled <b>Search</b> with a <b>Clear</b> button. The field must be focused as soon as the component mounts. <b>Clear</b> empties the field <em>and</em> puts focus back in it. Pressing <b>Escape</b> inside the field does the same as Clear.</p>",
    starter: "function SearchBox() {\n  // TODO: a ref to the input, an effect for the first focus\n  return (\n    <div>\n      <label>\n        Search <input />\n      </label>\n      <button>Clear</button>\n    </div>\n  );\n}\n\nfunction App() {\n  return <SearchBox />;\n}\n",
    hints: [
      "useRef gives you the DOM node once the component has mounted.",
      "ref.current.focus() inside a useEffect with [] runs after mount.",
      "The field can be controlled (value + onChange), or you can clear it through the ref.",
    ],
    solution: "function SearchBox() {\n  const ref = useRef(null);\n  const [value, setValue] = useState(\"\");\n\n  useEffect(() => {\n    ref.current.focus();\n  }, []);\n\n  function clear() {\n    setValue(\"\");\n    ref.current.focus();\n  }\n\n  return (\n    <div>\n      <label>\n        Search{\" \"}\n        <input\n          ref={ref}\n          value={value}\n          onChange={(e) => setValue(e.target.value)}\n          onKeyDown={(e) => e.key === \"Escape\" && clear()}\n        />\n      </label>\n      <button onClick={clear}>Clear</button>\n    </div>\n  );\n}\n\nfunction App() {\n  return <SearchBox />;\n}\n",
    tests: [
      { name: "the field is focused on mount", body: "render(<SearchBox />);\nassert.equal(document.activeElement, screen.getByLabelText(\"Search\"));" },
      { name: "typing works", body: "render(<SearchBox />);\nawait type(screen.getByLabelText(\"Search\"), \"react\");\nassert.equal(screen.getByLabelText(\"Search\").value, \"react\");" },
      { name: "Clear empties the field", body: "render(<SearchBox />);\nawait type(screen.getByLabelText(\"Search\"), \"react\");\nawait click(screen.getByRole(\"button\", { name: \"Clear\" }));\nassert.equal(screen.getByLabelText(\"Search\").value, \"\");" },
      { name: "Clear returns focus to the field", body: "render(<SearchBox />);\nawait type(screen.getByLabelText(\"Search\"), \"x\");\nscreen.getByRole(\"button\", { name: \"Clear\" }).focus();\nawait click(screen.getByRole(\"button\", { name: \"Clear\" }));\nassert.equal(document.activeElement, screen.getByLabelText(\"Search\"));" },
      { name: "Escape clears the field", body: "render(<SearchBox />);\nconst input = screen.getByLabelText(\"Search\");\nawait type(input, \"abc\");\nawait press(input, \"Escape\");\nassert.equal(input.value, \"\");" },
      { name: "Escape keeps the focus in the field", body: "render(<SearchBox />);\nconst input = screen.getByLabelText(\"Search\");\nawait type(input, \"abc\");\nawait press(input, \"Escape\");\nassert.equal(document.activeElement, input);" },
      { name: "other keys do not clear it", body: "render(<SearchBox />);\nconst input = screen.getByLabelText(\"Search\");\nawait type(input, \"abc\");\nawait press(input, \"Enter\");\nassert.equal(input.value, \"abc\");" },
      { name: "it can be typed into again after clearing", body: "render(<SearchBox />);\nconst input = screen.getByLabelText(\"Search\");\nawait type(input, \"one\");\nawait click(screen.getByRole(\"button\", { name: \"Clear\" }));\nawait type(input, \"two\");\nassert.equal(input.value, \"two\");" },
    ],
  },
  {
    id: "ex-comp-scroll-bottom",
    chapter: "react-refs-depth",
    level: "advanced",
    kind: "component",
    title: "Keep a chat log scrolled to the newest message",
    brief: "<p><code>ChatLog({ messages })</code> shows its messages in a box that scrolls. Whenever the number of messages changes, scroll the box to the bottom so the newest one is in view. The box is 60px tall with <code>overflow-y: auto</code>; the starter already renders it. Use a ref and an effect, not a library.</p>",
    starter: "function ChatLog({ messages }) {\n  return (\n    <ul data-testid=\"log\" style={{ height: 60, overflowY: \"auto\", margin: 0, padding: 0, listStyle: \"none\" }}>\n      {messages.map((m, i) => (\n        <li key={i} style={{ height: 20 }}>\n          {m}\n        </li>\n      ))}\n    </ul>\n  );\n}\n\nfunction App() {\n  return <ChatLog messages={Array.from({ length: 12 }, (_, i) => \"Message \" + (i + 1))} />;\n}\n",
    hints: [
      "A ref on the scrolling element lets you set scrollTop.",
      "scrollTop = scrollHeight puts the bottom in view.",
      "Run it in an effect that depends on messages.length.",
    ],
    solution: "function ChatLog({ messages }) {\n  const ref = useRef(null);\n\n  useEffect(() => {\n    ref.current.scrollTop = ref.current.scrollHeight;\n  }, [messages.length]);\n\n  return (\n    <ul ref={ref} data-testid=\"log\" style={{ height: 60, overflowY: \"auto\", margin: 0, padding: 0, listStyle: \"none\" }}>\n      {messages.map((m, i) => (\n        <li key={i} style={{ height: 20 }}>\n          {m}\n        </li>\n      ))}\n    </ul>\n  );\n}\n\nfunction App() {\n  return <ChatLog messages={Array.from({ length: 12 }, (_, i) => \"Message \" + (i + 1))} />;\n}\n",
    tests: [
      { name: "the log renders its messages", body: "render(<ChatLog messages={[\"a\", \"b\"]} />);\nassert.equal(screen.getAllByRole(\"listitem\").length, 2);" },
      { name: "with enough messages it scrolls at all", body: "render(<ChatLog messages={Array.from({ length: 10 }, (_, i) => \"m\" + i)} />);\nconst log = screen.getByTestId(\"log\");\nassert.ok(log.scrollHeight > log.clientHeight);" },
      { name: "it starts scrolled to the bottom", body: "render(<ChatLog messages={Array.from({ length: 15 }, (_, i) => \"m\" + i)} />);\nconst log = screen.getByTestId(\"log\");\nassert.ok(log.scrollTop + log.clientHeight >= log.scrollHeight - 1, \"scrollTop \" + log.scrollTop);" },
      { name: "a new message scrolls to the bottom again", body: "const view = render(<ChatLog messages={Array.from({ length: 6 }, (_, i) => \"m\" + i)} />);\nconst log = screen.getByTestId(\"log\");\nview.rerender(<ChatLog messages={Array.from({ length: 14 }, (_, i) => \"m\" + i)} />);\nassert.ok(log.scrollTop + log.clientHeight >= log.scrollHeight - 1);" },
      { name: "adding messages one by one keeps following", body: "const view = render(<ChatLog messages={[\"m0\"]} />);\nconst log = screen.getByTestId(\"log\");\nfor (let n = 2; n <= 12; n++) {\n  view.rerender(<ChatLog messages={Array.from({ length: n }, (_, i) => \"m\" + i)} />);\n  assert.ok(log.scrollTop + log.clientHeight >= log.scrollHeight - 1, \"at \" + n);\n}" },
      { name: "the newest message is the last item", body: "render(<ChatLog messages={[\"first\", \"second\", \"third\"]} />);\nconst items = screen.getAllByRole(\"listitem\");\nassert.equal(items[items.length - 1].textContent, \"third\");" },
      { name: "an empty log does not crash", body: "render(<ChatLog messages={[]} />);\nassert.equal(screen.queryAllByRole(\"listitem\").length, 0);" },
      { name: "it uses the same element after an update (no remount)", body: "const view = render(<ChatLog messages={[\"a\"]} />);\nconst before = screen.getByTestId(\"log\");\nview.rerender(<ChatLog messages={[\"a\", \"b\"]} />);\nassert.equal(screen.getByTestId(\"log\"), before);" },
    ],
  },
  {
    id: "ex-comp-fetch-race",
    chapter: "react-data-fetching",
    level: "intermediate",
    kind: "component",
    title: "Load a user, without racing yourself",
    brief: "<p>Build <code>UserCard({ id })</code>. It fetches <code>/api/users/ID</code> (the JSON has a <code>name</code>). While loading it shows <code>Loading…</code>; when ready it shows the name in an <code>&lt;h2&gt;</code>; if the request fails (network error <em>or</em> a non-OK response) it shows <code>Could not load user</code>. When <code>id</code> changes, the earlier request must be <b>aborted</b> and its result must never appear, even if it arrives last. An aborted request is not an error.</p>",
    starter: "function UserCard({ id }) {\n  // TODO: fetch in an effect, and clean up\n  return <p>Loading…</p>;\n}\n\nfunction App() {\n  return <UserCard id={1} />;\n}\n",
    hints: [
      "Start the request in useEffect with [id] as the dependency.",
      "Create an AbortController per effect run; return () => controller.abort().",
      "An abort rejects with an error whose name is AbortError: ignore that one.",
    ],
    solution: "function UserCard({ id }) {\n  const [state, setState] = useState({ status: \"loading\" });\n\n  useEffect(() => {\n    const controller = new AbortController();\n    setState({ status: \"loading\" });\n    fetch(\"/api/users/\" + id, { signal: controller.signal })\n      .then((res) => {\n        if (!res.ok) throw new Error(\"bad status\");\n        return res.json();\n      })\n      .then((user) => setState({ status: \"ready\", user }))\n      .catch((err) => {\n        if (err.name !== \"AbortError\") setState({ status: \"error\" });\n      });\n    return () => controller.abort();\n  }, [id]);\n\n  if (state.status === \"loading\") return <p>Loading…</p>;\n  if (state.status === \"error\") return <p>Could not load user</p>;\n  return <h2>{state.user.name}</h2>;\n}\n\nfunction App() {\n  return <UserCard id={1} />;\n}\n",
    tests: [
      { name: "it shows loading, then the name", body: "mockFetch(() => ({ name: \"Ana\" }));\nrender(<UserCard id={1} />);\nassert.ok(screen.getByText(\"Loading…\"));\nassert.ok(await screen.findByRole(\"heading\", { name: \"Ana\" }));\nassert.equal(screen.queryByText(\"Loading…\"), null);" },
      { name: "it requests the right URL", body: "const { calls } = mockFetch(() => ({ name: \"Ana\" }));\nrender(<UserCard id={7} />);\nawait screen.findByRole(\"heading\");\nassert.equal(calls[0].url, \"/api/users/7\");" },
      { name: "a non-OK response shows the error", body: "mockFetch(() => jsonResponse({}, 500));\nrender(<UserCard id={1} />);\nassert.ok(await screen.findByText(\"Could not load user\"));" },
      { name: "a network failure shows the error", body: "mockFetch(() => { throw new Error(\"offline\"); });\nrender(<UserCard id={1} />);\nassert.ok(await screen.findByText(\"Could not load user\"));" },
      { name: "changing the id fetches the new user", body: "mockFetch((url) => ({ name: url.endsWith(\"/1\") ? \"One\" : \"Two\" }));\nconst view = render(<UserCard id={1} />);\nawait screen.findByRole(\"heading\", { name: \"One\" });\nview.rerender(<UserCard id={2} />);\nassert.ok(await screen.findByRole(\"heading\", { name: \"Two\" }));" },
      { name: "a slow earlier request never overwrites the newer one", body: "mockFetch((url) => url.endsWith(\"/1\") ? delay(120, { name: \"Slow One\" }) : delay(10, { name: \"Fast Two\" }));\nconst view = render(<UserCard id={1} />);\nview.rerender(<UserCard id={2} />);\nassert.ok(await screen.findByRole(\"heading\", { name: \"Fast Two\" }));\nawait sleep(200);\nassert.ok(screen.getByRole(\"heading\", { name: \"Fast Two\" }));\nassert.equal(screen.queryByText(\"Slow One\"), null);" },
      { name: "the earlier request is aborted", body: "const { calls } = mockFetch(() => delay(100, { name: \"x\" }));\nconst view = render(<UserCard id={1} />);\nview.rerender(<UserCard id={2} />);\nawait sleep(20);\nassert.equal(calls[0].init.signal.aborted, true);\nassert.equal(calls[1].init.signal.aborted, false);" },
      { name: "an aborted request does not show the error", body: "mockFetch((url) => url.endsWith(\"/1\") ? delay(80, { name: \"One\" }) : delay(10, { name: \"Two\" }));\nconst view = render(<UserCard id={1} />);\nawait sleep(5);\nview.rerender(<UserCard id={2} />);\nawait sleep(150);\nassert.equal(screen.queryByText(\"Could not load user\"), null);\nassert.ok(screen.getByRole(\"heading\", { name: \"Two\" }));" },
      { name: "it shows loading again when the id changes", body: "mockFetch(() => delay(60, { name: \"x\" }));\nconst view = render(<UserCard id={1} />);\nawait screen.findByRole(\"heading\");\nview.rerender(<UserCard id={2} />);\nassert.ok(await screen.findByText(\"Loading…\"));" },
    ],
  },
  {
    id: "ex-comp-window-listener",
    chapter: "react-useeffect-basics",
    level: "intermediate",
    kind: "component",
    title: "Subscribe to the window, and unsubscribe",
    brief: "<p>Build <code>WindowWidth</code>: it shows <code>Width: N</code> where N is <code>window.innerWidth</code>, and updates whenever the window fires a <code>resize</code> event. Add the listener once, and remove the very same function when the component unmounts.</p>",
    starter: "function WindowWidth() {\n  // TODO: state for the width, an effect that listens for resize\n  return <p>Width: {window.innerWidth}</p>;\n}\n\nfunction App() {\n  return <WindowWidth />;\n}\n",
    hints: [
      "Initialise state from window.innerWidth.",
      "Define the handler inside the effect so you can pass the same function to removeEventListener.",
      "Return the cleanup from the effect.",
    ],
    solution: "function WindowWidth() {\n  const [width, setWidth] = useState(window.innerWidth);\n\n  useEffect(() => {\n    function onResize() {\n      setWidth(window.innerWidth);\n    }\n    window.addEventListener(\"resize\", onResize);\n    return () => window.removeEventListener(\"resize\", onResize);\n  }, []);\n\n  return <p>Width: {width}</p>;\n}\n\nfunction App() {\n  return <WindowWidth />;\n}\n",
    tests: [
      { name: "it shows the current width", body: "render(<WindowWidth />);\nassert.ok(screen.getByText(\"Width: \" + window.innerWidth));" },
      { name: "a resize updates it", body: "render(<WindowWidth />);\nObject.defineProperty(window, \"innerWidth\", { value: 512, configurable: true });\nflushSync(() => window.dispatchEvent(new Event(\"resize\")));\nassert.ok(screen.getByText(\"Width: 512\"));" },
      { name: "several resizes in a row", body: "render(<WindowWidth />);\nfor (const w of [300, 640, 1024]) {\n  Object.defineProperty(window, \"innerWidth\", { value: w, configurable: true });\n  flushSync(() => window.dispatchEvent(new Event(\"resize\")));\n  assert.ok(screen.getByText(\"Width: \" + w));\n}" },
      { name: "one resize listener is added, however often it re-renders", body: "const added = [];\nconst orig = window.addEventListener;\nwindow.addEventListener = function (type, fn, ...rest) { if (type === \"resize\") added.push(fn); return orig.call(this, type, fn, ...rest); };\ntry {\n  render(<WindowWidth />);\n  for (const w of [400, 500, 600]) {\n    Object.defineProperty(window, \"innerWidth\", { value: w, configurable: true });\n    flushSync(() => window.dispatchEvent(new Event(\"resize\")));\n  }\n} finally {\n  window.addEventListener = orig;\n}\nassert.equal(added.length, 1);" },
      { name: "the same listener is removed on unmount", body: "const added = [];\nconst removed = [];\nconst oAdd = window.addEventListener;\nconst oRemove = window.removeEventListener;\nwindow.addEventListener = function (type, fn, ...rest) { if (type === \"resize\") added.push(fn); return oAdd.call(this, type, fn, ...rest); };\nwindow.removeEventListener = function (type, fn, ...rest) { if (type === \"resize\") removed.push(fn); return oRemove.call(this, type, fn, ...rest); };\ntry {\n  const view = render(<WindowWidth />);\n  view.unmount();\n} finally {\n  window.addEventListener = oAdd;\n  window.removeEventListener = oRemove;\n}\nassert.equal(added.length, 1);\nassert.equal(removed.length, 1);\nassert.equal(added[0], removed[0]);" },
      { name: "no work happens after unmount", body: "let calls = 0;\nconst oAdd = window.addEventListener;\nlet handler;\nwindow.addEventListener = function (type, fn, ...rest) { if (type === \"resize\") handler = fn; return oAdd.call(this, type, fn, ...rest); };\ntry {\n  const view = render(<WindowWidth />);\n  view.unmount();\n} finally {\n  window.addEventListener = oAdd;\n}\nlet threw = false;\ntry { window.dispatchEvent(new Event(\"resize\")); } catch (e) { threw = true; }\nassert.equal(threw, false);" },
      { name: "two components each track the width", body: "render(<><WindowWidth /><WindowWidth /></>);\nObject.defineProperty(window, \"innerWidth\", { value: 777, configurable: true });\nflushSync(() => window.dispatchEvent(new Event(\"resize\")));\nassert.equal(screen.getAllByText(\"Width: 777\").length, 2);" },
    ],
  },
  {
    id: "ex-comp-document-title",
    chapter: "react-useeffect-basics",
    level: "intermediate",
    kind: "component",
    title: "Keep the tab title in sync",
    brief: "<p>Build <code>Page({ title, children })</code>. While it is mounted, <code>document.title</code> is <code>TITLE | Groundwork</code>. When <code>title</code> changes the tab title follows, and when the component unmounts the title goes back to whatever it was before.</p>",
    starter: "function Page({ title, children }) {\n  // TODO: an effect that sets document.title\n  return <main>{children}</main>;\n}\n\nfunction App() {\n  return <Page title=\"Home\">Welcome</Page>;\n}\n",
    hints: [
      "document.title is an ordinary string you can assign inside an effect.",
      "Save the old title before changing it, and restore it in the cleanup.",
      "Depend on [title].",
    ],
    solution: "function Page({ title, children }) {\n  useEffect(() => {\n    const previous = document.title;\n    document.title = title + \" | Groundwork\";\n    return () => {\n      document.title = previous;\n    };\n  }, [title]);\n  return <main>{children}</main>;\n}\n\nfunction App() {\n  return <Page title=\"Home\">Welcome</Page>;\n}\n",
    tests: [
      { name: "it renders its children", body: "render(<Page title=\"Home\">Welcome</Page>);\nassert.ok(screen.getByText(\"Welcome\"));" },
      { name: "it sets the tab title", body: "document.title = \"start\";\nrender(<Page title=\"Home\">x</Page>);\nassert.equal(document.title, \"Home | Groundwork\");" },
      { name: "a new title replaces the old one", body: "document.title = \"start\";\nconst view = render(<Page title=\"Home\">x</Page>);\nview.rerender(<Page title=\"About\">x</Page>);\nassert.equal(document.title, \"About | Groundwork\");" },
      { name: "unmounting restores the previous title", body: "document.title = \"start\";\nconst view = render(<Page title=\"Home\">x</Page>);\nview.unmount();\nassert.equal(document.title, \"start\");" },
      { name: "changing the title and then unmounting still restores the original", body: "document.title = \"original\";\nconst view = render(<Page title=\"A\">x</Page>);\nview.rerender(<Page title=\"B\">x</Page>);\nview.rerender(<Page title=\"C\">x</Page>);\nview.unmount();\nassert.equal(document.title, \"original\");" },
      { name: "re-rendering with the same title does not touch the document", body: "document.title = \"start\";\nconst view = render(<Page title=\"Same\">x</Page>);\nconst setter = Object.getOwnPropertyDescriptor(Document.prototype, \"title\");\nlet writes = 0;\nObject.defineProperty(document, \"title\", { configurable: true, get() { return setter.get.call(document); }, set(v) { writes++; setter.set.call(document, v); } });\ntry {\n  view.rerender(<Page title=\"Same\">y</Page>);\n  view.rerender(<Page title=\"Same\">z</Page>);\n} finally {\n  delete document.title;\n}\nassert.equal(writes, 0);" },
      { name: "the title is set in the same commit as the first render", body: "document.title = \"start\";\nrender(<Page title=\"Fast\">x</Page>);\nassert.equal(document.title, \"Fast | Groundwork\");" },
      { name: "nested pages: the inner title wins while it is mounted", body: "document.title = \"start\";\nrender(<Page title=\"Outer\"><Page title=\"Inner\">x</Page></Page>);\nassert.ok(document.title === \"Inner | Groundwork\" || document.title === \"Outer | Groundwork\");" },
    ],
  },
];
