import type { Chapter } from "../types";

export const archRepoMap: Chapter = {
  id: "arch-repo-map",
  num: "B3",
  title: "Where everything lives",
  short: "Where things live",
  levels: ["beginner"],
  practice: [],
  ready: true,
  subtitle: "Ten directories, the rule each one follows, and the places the rules bend.",
  body: `<h3>The map</h3>
<p>
  The repository holds 552 tracked files. Nearly all of them sit in four directories, and the split
  between those four is the most useful thing to know before opening anything. The counts are from
  <code>git ls-files</code> at commit <code>d6b12d7</code>.
</p>
<div class="table-scroll"><table>
<thead><tr><th>Directory</th><th>Files</th><th>What is in it</th><th>The rule</th></tr></thead>
<tbody>
<tr><td><code>app/</code></td><td>159</td><td>Routes: one folder per topic, the tools, the four API routes, and the metadata files</td><td>A route's <code>page.tsx</code> is a server component; the interactive part sits next to it as a client view</td></tr>
<tr><td><code>components/</code></td><td>47</td><td>UI shared by more than one route: the two page frames, the reader, the playground</td><td>A component marked <code>"use client"</code> must earn it</td></tr>
<tr><td><code>lib/</code></td><td>78</td><td>Logic with no markup: content access, storage, runners and workers, and the engines</td><td>The engines are pure functions, so they can be tested without a browser</td></tr>
<tr><td><code>content/</code></td><td>212</td><td>Every word on the site, and every exercise, as typed TypeScript: 5.4 MB of it</td><td>Read through <code>lib/</code>, not by pages</td></tr>
<tr><td><code>public/</code></td><td>0</td><td>The TypeScript lib files and the React sandbox bundle</td><td>Generated by scripts before every build and ignored by git</td></tr>
<tr><td><code>scripts/</code></td><td>4</td><td>The two prebuild steps, the comment checker, and a Vercel clean-up tool</td><td>Plain Node, run by npm lifecycle hooks, git hooks or CI</td></tr>
<tr><td><code>tests/</code></td><td>15</td><td>Vitest</td><td>Tests data and pure logic, not components</td></tr>
<tr><td><code>e2e/</code></td><td>5</td><td>Playwright: 3 specs and an audio fixture for the narrator</td><td>A real browser against a production build</td></tr>
<tr><td><code>docs/</code></td><td>3</td><td>The roadmap and an audit</td><td>Not shipped to readers</td></tr>
<tr><td><code>.github/</code></td><td>3</td><td>CI, a Vercel clean-up workflow, and Dependabot</td><td>CI runs typecheck, lint, formatting, spelling and Vitest, then a build, Playwright and Lighthouse</td></tr>
</tbody>
</table></div>

<h3>Which way the imports point</h3>

<figure>
<svg viewBox="0 0 900 300" class="dg" role="img" aria-label="Content is read by lib. Lib is read by app routes, by components and by the tests. App routes render components. A script writes the generated files in public.">
<g class="rough">
<rect x="30" y="120" width="150" height="64" rx="10" style="fill: var(--dg-box-green); stroke: var(--green); stroke-width: 2" />
<rect x="250" y="120" width="170" height="64" rx="10" style="fill: var(--sheet); stroke: var(--ink); stroke-width: 2" />
<rect x="500" y="40" width="180" height="64" rx="10" style="fill: var(--sheet); stroke: var(--ink); stroke-width: 2" />
<rect x="500" y="200" width="180" height="64" rx="10" style="fill: var(--sheet); stroke: var(--ink); stroke-width: 2" />
<rect x="250" y="236" width="170" height="50" rx="10" style="fill: var(--sheet-2); stroke: var(--line-soft); stroke-width: 1.6" />
<rect x="740" y="40" width="140" height="64" rx="10" style="fill: var(--sheet-2); stroke: var(--line-soft); stroke-width: 1.6" />
<rect x="740" y="200" width="140" height="64" rx="10" style="fill: var(--sheet-2); stroke: var(--line-soft); stroke-width: 1.6" />
<path class="ln" d="M180 152 H244" marker-end="url(#arrow)" />
<path class="ln" d="M420 140 C460 140 460 72 494 72" marker-end="url(#arrow)" />
<path class="ln" d="M420 164 C460 164 460 232 494 232" marker-end="url(#arrow)" />
<path class="ln" d="M590 104 V194" marker-end="url(#arrow)" />
<path class="ln" d="M335 184 V230" marker-end="url(#arrow)" />
<path class="ln" d="M810 104 V194" marker-end="url(#arrow)" />
</g>
<text class="lbl" x="105" y="148" text-anchor="middle">content/</text>
<text class="sm" x="105" y="170" text-anchor="middle">212 files</text>
<text class="lbl" x="335" y="148" text-anchor="middle">lib/</text>
<text class="sm" x="335" y="170" text-anchor="middle">78 files</text>
<text class="lbl" x="590" y="68" text-anchor="middle">app/</text>
<text class="sm" x="590" y="90" text-anchor="middle">159 files</text>
<text class="lbl" x="590" y="228" text-anchor="middle">components/</text>
<text class="sm" x="590" y="250" text-anchor="middle">47 files</text>
<text class="lbl" x="335" y="266" text-anchor="middle">tests/</text>
<text class="lbl" x="810" y="68" text-anchor="middle">scripts/</text>
<text class="sm" x="810" y="90" text-anchor="middle">2 prebuild steps</text>
<text class="lbl" x="810" y="228" text-anchor="middle">public/wasm/</text>
<text class="sm" x="810" y="250" text-anchor="middle">generated</text>
<text class="sm" x="602" y="154">renders</text>
<text class="sm" x="822" y="154">writes</text>
<text class="sm" x="30" y="30">An arrow points from what is read to what reads it.</text>
</svg>
<figcaption>
  Content flows one way. Nothing in <code>content/</code> imports code, and pages ask <code>lib/</code>
  for chapters rather than reaching into the files themselves.
</figcaption>
</figure>

<p>
  The rule has three exceptions, and they are worth knowing because each one is a small cost someone
  accepted. <code>app/git/</code> imports <code>content/git-body.ts</code> directly, because the Git
  guide is one pre-written HTML string rather than chapters, so there is nothing for <code>lib/</code> to
  do. <code>app/mock/Room.tsx</code> dynamically imports <code>content/practice</code> in the browser the
  first time a coding question appears, so it can hand the full exercise to the editor; that is the
  whole exercise set, downloaded once, on the one screen that needs it. And
  <code>lib/practiceLinks.ts</code> imports a type from <code>app/practice/</code>, the only place
  <code>lib/</code> looks upward.
</p>

<h3>Inside app/</h3>
<p>
  Twenty of the route folders are topics, and each has the same four things: <code>page.tsx</code> for
  the cover, <code>[chapter]/page.tsx</code>, <code>[chapter]/loading.tsx</code> for the skeleton, and
  <code>search-index.json/route.ts</code>. Each of those files is a few lines that call into
  <code>components/reader/topicPages.tsx</code>, so the twenty folders are copies of one shape rather than
  twenty implementations. The architecture folder is the one without a <code>loading.tsx</code>.
</p>
<p>
  The tools are different. <code>app/mock/</code> has 14 files besides its page: the lobby, the loop
  wizard, the room, the scorecard, the readiness dashboard, a timer ring, a small design whiteboard, and
  the hook that fetches question banks. <code>app/whiteboard/</code> has 11, led by
  <code>Board.tsx</code> at 1,851 lines, the largest component in the repository. They live with their
  routes because nothing else uses them. <a href="/architecture/arch-routes">The routes chapter</a> walks
  the whole tree.
</p>

<h3>Inside components/ and lib/</h3>
<div class="table-scroll"><table>
<thead><tr><th>Where</th><th>What</th></tr></thead>
<tbody>
<tr><td><code>components/Shell.tsx</code></td><td>The frame with the sidebar, used by reading pages and a few others</td></tr>
<tr><td><code>components/SiteDrawer.tsx</code>, <code>AppHeader.tsx</code></td><td>The frame for full-screen tools: a slide-in menu instead of a sidebar</td></tr>
<tr><td><code>components/Modal.tsx</code>, <code>AppearancePicker.tsx</code></td><td>Dialogs on the native <code>&lt;dialog&gt;</code> element, and the theme and handwriting picker shared by the playground and the whiteboard</td></tr>
<tr><td><code>components/reader/</code></td><td>15 files: the chapter view, the cover map, search, narration</td></tr>
<tr><td><code>components/practice/</code></td><td>10 files, led by <code>PracticeWorkspace.tsx</code> at 1,735 lines and <code>CodeEditor.tsx</code> at 1,112</td></tr>
<tr><td><code>lib/polyglot/</code></td><td>Records test cases from JavaScript solutions and grades other languages against them</td></tr>
<tr><td><code>lib/mock/</code></td><td>12 files: loops, pacing, scoring, readiness and the session reducer of the mock interview</td></tr>
<tr><td><code>lib/whiteboard/</code></td><td>The board's element model, geometry, export and storage</td></tr>
<tr><td><code>lib/debug/</code>, <code>lib/editor/</code></td><td>The step-through debugger's instrumentation, and the editor's lint and format worker</td></tr>
<tr><td><code>lib/*Worker.ts</code>, <code>lib/*Runner.ts</code></td><td>One runner per language family on the page side, and the three execution workers behind them</td></tr>
</tbody>
</table></div>
<p>
  There are two whiteboards. <code>lib/whiteboard/</code> is the full board at <code>/whiteboard</code>,
  with freehand, fifteen element kinds and arrows that stay attached. <code>lib/mock/board.ts</code> is a
  much smaller one inside the mock interview's design round: boxes, databases, queues and arrows,
  serialised into the interview session so the scorecard can draw it again. The cost of keeping them
  apart is two drawings of boxes and arrows. The benefit is that the interview's board model is 84
  lines and cannot break when the 1,851-line board changes.
</p>

<h3>The content directory in detail</h3>
<pre><code>content/
  types.ts              &larr; every content type
  topics.ts             &larr; the shelf: topics, levels, syllabus
  notes.ts              &larr; barrel for JavaScript (served at /notes)
  js/                   &larr; 41 chapter files
  react-notes.ts, react/          &larr; 57
  dsa-notes.ts, dsa/              &larr; 34
  system-design-notes.ts, system-design/  &larr; 24
  architecture-notes.ts, architecture/    &larr; this topic
  html-notes.ts ... kubernetes-notes.ts   &larr; outlines only
  interview-data.ts     &larr; the interview book, its own record shape
  git-body.ts           &larr; the Git guide, one HTML string
  practice.ts           &larr; barrel over the exercise groups
  practice/
    js-fundamentals.ts, js-applied.ts
    dsa.ts + dsa-1.ts ... dsa-8.ts
    react.ts, react-components.ts</code></pre>

<p>
  It did not start that way. Four files had grown past the point where an editor is comfortable: the
  exercises were 840 KB in one file, the DSA notes 626 KB, system design 577 KB and the JavaScript notes
  306 KB. They were split by walking the TypeScript AST and moving each chapter's <em>source text</em>
  into its own file, so the formatting survived and the assembled data came out byte-for-byte identical
  to what it had been.
</p>

<div class="bx is-ref">
<span class="ttl">Why the split had to be textual</span>
<p>
  The obvious way to split a data file is to import it, then write each piece back out as JSON. That
  would have turned hundreds of kilobytes of readable HTML bodies, written as template literals with
  real newlines, into one escaped line each: making the files worse rather than better, while fixing
  the size. Moving the source text instead keeps every line where the author put it.
</p>
</div>

<h3>The files that are still large</h3>
<p>
  <code>content/interview-data.ts</code> is 430,468 bytes, the largest tracked file after <code>package-lock.json</code>. It has
  its own record shape, one object per round with questions, answers, traps and follow-ups, and it is
  written one field per line on purpose, which is why <code>.prettierignore</code> lists it:
  formatting it would explode it into thousands of lines without changing what a reader sees. The
  exercise files are next. <code>content/practice/react-components.ts</code> is 387,720 bytes, and the
  whole <code>content/practice/</code> folder is also in <code>.prettierignore</code>.
  <code>content/topics.ts</code>, at 181,034 bytes, used to be ignored too; it is now formatted like
  everything else.
</p>`,
};
